[build-system]
requires = [
  "setuptools >= 42",
  "wheel",
  "setuptools_scm[toml]>=3.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "napari/_version.py"

[tool.briefcase]
project_name = "napari"
bundle = "com.napari"
author = "napari"
url = "https://napari.org/"
license = "BSD license"
# version populated in bundle.py

[tool.briefcase.app.napari]
formal_name = "napari"
description = "napari: a multi-dimensional image viewer"
sources = ['napari']
icon = "resources/icon"
requires = [
  "appdirs>=1.4.4",
  "cachey>=0.2.1",
  "dask[array]>=2.1.0",
  "imageio>=2.5.0",
  "importlib-metadata>=1.5.0 ; python_version < '3.8'",
  "ipykernel>=5.1.1",
  "IPython>=7.7.0",
  "napari-plugin-engine>=0.1.5",
  "napari-svg>=0.1.3",
  "numpy>=1.10.0",
  "numpydoc>=0.9.2",
  "Pillow!=7.1.0,!=7.1.1",
  "psutil>=5.0",
  "PyOpenGL>=3.1.0",
  "PyYAML>=5.1",
  "qtconsole>=4.5.1",
  "qtpy>=1.7.0",
  "scipy>=1.2.0",
  "tifffile>=2020.2.16",
  "toolz>=0.10.0",
  "typing_extensions",
  "vispy>=0.6.4",
  "wrapt>=1.11.1",
  # added in bundle
  "pip",
  "PySide2==5.14.2.2",
  "scikit-image",
  "zarr",
]


[tool.black]
target-version = ['py36', 'py37', 'py38']
skip-string-normalization = true
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | examples
    | vendored
  )/
  | napari/resources/qt.py
)
'''

[tool.check-manifest]
ignore = [
  "bundle.py",
  ".cirrus.yml",
  ".pre-commit-config.yaml",
  "asv.conf.json",
  "codecov.yml",
  "Makefile",
  "napari/_version.py",  # added during build by setuptools_scm
]

[tool.isort]
profile = "black"
line_length = 79
skip_glob = ["*examples/*", "*vendored*"]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore::DeprecationWarning:ipykernel",
  "ignore::DeprecationWarning:skimage.util.dtype:226",
  "ignore:QFontMetrics.width::qtconsole",
  "ignore:Accessing zmq Socket:DeprecationWarning:jupyter_client"
]
markers = [
    "perfmon: marks tests that require perfmon to be enabled"
]

