{% set data = load_setup_py_data() %}
{% set name = "orange3-singlecell" %}
{% set version = data['version'] %}

package:
  name: {{ name|lower }}
  version: {{ data['version'] }}

source:
  git_url: ../../

build:
  number: 0
  noarch: python
  script:
    - cd doc && make htmlhelp && cd ..
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - sphinx
    - recommonmark
    - setuptools
  run:
    - python
    - orange3
    - networkx

test:
  imports:
    - orangecontrib.single_cell.__main__
  commands:
    - python -m orangecontrib.single_cell --help
    - test -f $PREFIX/help/orange3-single_cell/index.html  # [unix]
about:
  home: https://singlecell.biolab.si/
  license: GPL-3
  license_family: GPL
  license_file: LICENSE
  summary: 'Single-cell Orange'

extra:
  recipe-maintainers:
    - astaric
