# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_Validation.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 492)
        Dialog.setMouseTracking(False)
        Dialog.setStyleSheet("background-color: rgb(165, 181, 209);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.Validation_time_trace = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Validation_time_trace.sizePolicy().hasHeightForWidth())
        self.Validation_time_trace.setSizePolicy(sizePolicy)
        self.Validation_time_trace.setMinimumSize(QtCore.QSize(180, 180))
        self.Validation_time_trace.setMaximumSize(QtCore.QSize(800, 500))
        self.Validation_time_trace.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Validation_time_trace.setObjectName("Validation_time_trace")
        self.gridLayout.addWidget(self.Validation_time_trace, 0, 0, 1, 8)
        self.Validation_container = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Validation_container.sizePolicy().hasHeightForWidth())
        self.Validation_container.setSizePolicy(sizePolicy)
        self.Validation_container.setMinimumSize(QtCore.QSize(180, 180))
        self.Validation_container.setMaximumSize(QtCore.QSize(800, 500))
        self.Validation_container.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Validation_container.setObjectName("Validation_container")
        self.gridLayout.addWidget(self.Validation_container, 1, 0, 1, 8)
        self.Nois_validation_Points = QtWidgets.QSpinBox(Dialog)
        self.Nois_validation_Points.setMinimumSize(QtCore.QSize(50, 20))
        self.Nois_validation_Points.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Nois_validation_Points.setFont(font)
        self.Nois_validation_Points.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Ubuntu\";")
        self.Nois_validation_Points.setMinimum(1)
        self.Nois_validation_Points.setMaximum(200)
        self.Nois_validation_Points.setSingleStep(2)
        self.Nois_validation_Points.setProperty("value", 10)
        self.Nois_validation_Points.setObjectName("Nois_validation_Points")
        self.gridLayout.addWidget(self.Nois_validation_Points, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.Noise_level_validation = QtWidgets.QDoubleSpinBox(Dialog)
        self.Noise_level_validation.setMinimumSize(QtCore.QSize(50, 20))
        self.Noise_level_validation.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Noise_level_validation.setFont(font)
        self.Noise_level_validation.setStyleSheet("font: 8pt \"Ubuntu\";\n"
"background-color: rgb(255, 255, 255);")
        self.Noise_level_validation.setDecimals(1)
        self.Noise_level_validation.setMaximum(10.0)
        self.Noise_level_validation.setSingleStep(0.1)
        self.Noise_level_validation.setProperty("value", 0.5)
        self.Noise_level_validation.setObjectName("Noise_level_validation")
        self.gridLayout.addWidget(self.Noise_level_validation, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 4, 1, 1)
        self.Enable_noise_validation = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Enable_noise_validation.setFont(font)
        self.Enable_noise_validation.setObjectName("Enable_noise_validation")
        self.gridLayout.addWidget(self.Enable_noise_validation, 2, 5, 1, 1)
        self.Prune_value = QtWidgets.QDoubleSpinBox(Dialog)
        self.Prune_value.setMinimumSize(QtCore.QSize(50, 20))
        self.Prune_value.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Prune_value.setFont(font)
        self.Prune_value.setStyleSheet("font: 8pt \"Ubuntu\";\n"
"background-color: rgb(255, 255, 255);")
        self.Prune_value.setDecimals(2)
        self.Prune_value.setMinimum(1.01)
        self.Prune_value.setMaximum(3.0)
        self.Prune_value.setSingleStep(0.01)
        self.Prune_value.setProperty("value", 1.1)
        self.Prune_value.setObjectName("Prune_value")
        self.gridLayout.addWidget(self.Prune_value, 2, 6, 1, 1)
        self.Enable_prune = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Enable_prune.setFont(font)
        self.Enable_prune.setMouseTracking(True)
        self.Enable_prune.setToolTip("<html><head/><body><p>Leave out solution with RMS above the defined pruning level</p></body></html>")
        self.Enable_prune.setToolTipDuration(-1)
        self.Enable_prune.setStatusTip("")
        self.Enable_prune.setWhatsThis("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Leave out solution with rms above the pruning level</p></body></html>")
        self.Enable_prune.setObjectName("Enable_prune")
        self.gridLayout.addWidget(self.Enable_prune, 2, 7, 1, 1)
        self.Bg_dim_validation_points = QtWidgets.QSpinBox(Dialog)
        self.Bg_dim_validation_points.setMinimumSize(QtCore.QSize(50, 20))
        self.Bg_dim_validation_points.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Bg_dim_validation_points.setFont(font)
        self.Bg_dim_validation_points.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Ubuntu\";")
        self.Bg_dim_validation_points.setMinimum(2)
        self.Bg_dim_validation_points.setMaximum(200)
        self.Bg_dim_validation_points.setSingleStep(2)
        self.Bg_dim_validation_points.setProperty("value", 5)
        self.Bg_dim_validation_points.setObjectName("Bg_dim_validation_points")
        self.gridLayout.addWidget(self.Bg_dim_validation_points, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.Bg_dimension_range = QtWidgets.QDoubleSpinBox(Dialog)
        self.Bg_dimension_range.setMinimumSize(QtCore.QSize(50, 20))
        self.Bg_dimension_range.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Bg_dimension_range.setFont(font)
        self.Bg_dimension_range.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Bg_dimension_range.setPrefix("")
        self.Bg_dimension_range.setSuffix("")
        self.Bg_dimension_range.setMinimum(0.0)
        self.Bg_dimension_range.setMaximum(5.0)
        self.Bg_dimension_range.setSingleStep(0.01)
        self.Bg_dimension_range.setProperty("value", 0.1)
        self.Bg_dimension_range.setObjectName("Bg_dimension_range")
        self.gridLayout.addWidget(self.Bg_dimension_range, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 4, 1, 1)
        self.Enable_Bg_dim_valid = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Enable_Bg_dim_valid.setFont(font)
        self.Enable_Bg_dim_valid.setObjectName("Enable_Bg_dim_valid")
        self.gridLayout.addWidget(self.Enable_Bg_dim_valid, 3, 5, 1, 1)
        self.Validate_Button = QtWidgets.QPushButton(Dialog)
        self.Validate_Button.setMinimumSize(QtCore.QSize(50, 20))
        self.Validate_Button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Validate_Button.setSizeIncrement(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Validate_Button.setFont(font)
        self.Validate_Button.setObjectName("Validate_Button")
        self.gridLayout.addWidget(self.Validate_Button, 3, 6, 1, 2)
        self.BG_validation_trials = QtWidgets.QSpinBox(Dialog)
        self.BG_validation_trials.setMinimumSize(QtCore.QSize(50, 20))
        self.BG_validation_trials.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.BG_validation_trials.setFont(font)
        self.BG_validation_trials.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Ubuntu\";")
        self.BG_validation_trials.setMinimum(2)
        self.BG_validation_trials.setMaximum(200)
        self.BG_validation_trials.setSingleStep(2)
        self.BG_validation_trials.setProperty("value", 20)
        self.BG_validation_trials.setObjectName("BG_validation_trials")
        self.gridLayout.addWidget(self.BG_validation_trials, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 2, 1, 1)
        self.Bg_valiation_range = QtWidgets.QSpinBox(Dialog)
        self.Bg_valiation_range.setMinimumSize(QtCore.QSize(50, 20))
        self.Bg_valiation_range.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Bg_valiation_range.setFont(font)
        self.Bg_valiation_range.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 8pt \"Ubuntu\";")
        self.Bg_valiation_range.setMinimum(4)
        self.Bg_valiation_range.setMaximum(10000)
        self.Bg_valiation_range.setProperty("value", 200)
        self.Bg_valiation_range.setObjectName("Bg_valiation_range")
        self.gridLayout.addWidget(self.Bg_valiation_range, 4, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 4, 1, 1)
        self.Enable_Bg_range_valid = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Enable_Bg_range_valid.setFont(font)
        self.Enable_Bg_range_valid.setObjectName("Enable_Bg_range_valid")
        self.gridLayout.addWidget(self.Enable_Bg_range_valid, 4, 5, 1, 1)
        self.Validate_Save_Button = QtWidgets.QPushButton(Dialog)
        self.Validate_Save_Button.setMinimumSize(QtCore.QSize(50, 20))
        self.Validate_Save_Button.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Validate_Save_Button.setSizeIncrement(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Validate_Save_Button.setFont(font)
        self.Validate_Save_Button.setObjectName("Validate_Save_Button")
        self.gridLayout.addWidget(self.Validate_Save_Button, 4, 6, 1, 2)
        self.Weighting_factor_trials = QtWidgets.QSpinBox(Dialog)
        self.Weighting_factor_trials.setMinimumSize(QtCore.QSize(50, 20))
        self.Weighting_factor_trials.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Weighting_factor_trials.setFont(font)
        self.Weighting_factor_trials.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(255, 255, 0);\n"
"font: 8pt \"Ubuntu\";")
        self.Weighting_factor_trials.setMinimum(2)
        self.Weighting_factor_trials.setMaximum(200)
        self.Weighting_factor_trials.setSingleStep(2)
        self.Weighting_factor_trials.setProperty("value", 10)
        self.Weighting_factor_trials.setObjectName("Weighting_factor_trials")
        self.gridLayout.addWidget(self.Weighting_factor_trials, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 2, 1, 1)
        self.Weighting_factor_validation = QtWidgets.QDoubleSpinBox(Dialog)
        self.Weighting_factor_validation.setMinimumSize(QtCore.QSize(50, 20))
        self.Weighting_factor_validation.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Weighting_factor_validation.setFont(font)
        self.Weighting_factor_validation.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Weighting_factor_validation.setPrefix("")
        self.Weighting_factor_validation.setSuffix("")
        self.Weighting_factor_validation.setMinimum(0.0)
        self.Weighting_factor_validation.setMaximum(5.0)
        self.Weighting_factor_validation.setSingleStep(0.01)
        self.Weighting_factor_validation.setProperty("value", 0.1)
        self.Weighting_factor_validation.setObjectName("Weighting_factor_validation")
        self.gridLayout.addWidget(self.Weighting_factor_validation, 5, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(71, 0))
        self.label_8.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 4, 1, 1)
        self.Enable_weighting_factor_validation = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Enable_weighting_factor_validation.setFont(font)
        self.Enable_weighting_factor_validation.setObjectName("Enable_weighting_factor_validation")
        self.gridLayout.addWidget(self.Enable_weighting_factor_validation, 5, 5, 1, 1)
        self.Exitbutton_Validation_GUI = QtWidgets.QPushButton(Dialog)
        self.Exitbutton_Validation_GUI.setMinimumSize(QtCore.QSize(50, 20))
        self.Exitbutton_Validation_GUI.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Exitbutton_Validation_GUI.setFont(font)
        self.Exitbutton_Validation_GUI.setObjectName("Exitbutton_Validation_GUI")
        self.gridLayout.addWidget(self.Exitbutton_Validation_GUI, 5, 6, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Validation"))
        self.label_5.setText(_translate("Dialog", "Trials"))
        self.label_12.setText(_translate("Dialog", "+"))
        self.label_6.setText(_translate("Dialog", "RMS white noise"))
        self.Enable_noise_validation.setText(_translate("Dialog", "Enabled"))
        self.Enable_prune.setText(_translate("Dialog", "Prune"))
        self.label_3.setText(_translate("Dialog", "Trials"))
        self.label_9.setText(_translate("Dialog", "±"))
        self.label_4.setText(_translate("Dialog", "Bg. dim"))
        self.Enable_Bg_dim_valid.setText(_translate("Dialog", "Enabled"))
        self.Validate_Button.setText(_translate("Dialog", "Validate"))
        self.label.setText(_translate("Dialog", "Trials"))
        self.label_10.setText(_translate("Dialog", "±"))
        self.label_2.setText(_translate("Dialog", "Bg. range / ns"))
        self.Enable_Bg_range_valid.setText(_translate("Dialog", "Enabled"))
        self.Validate_Save_Button.setText(_translate("Dialog", "Save"))
        self.label_7.setText(_translate("Dialog", "Trials"))
        self.label_11.setText(_translate("Dialog", "±"))
        self.label_8.setText(_translate("Dialog", "weighting fac."))
        self.Enable_weighting_factor_validation.setText(_translate("Dialog", "Enabled"))
        self.Exitbutton_Validation_GUI.setText(_translate("Dialog", "Exit"))

