# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GloPelMainGui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GloPel2017(object):
    def setupUi(self, GloPel2017):
        GloPel2017.setObjectName("GloPel2017")
        GloPel2017.resize(926, 589)
        GloPel2017.setMaximumSize(QtCore.QSize(16777215, 1000))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 213, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(63, 191, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        GloPel2017.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        GloPel2017.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../GloPel_Python_New_Layout/icon_logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GloPel2017.setWindowIcon(icon)
        GloPel2017.setWindowOpacity(4.0)
        GloPel2017.setAutoFillBackground(False)
        GloPel2017.setStyleSheet("background-color: rgb(190, 209, 240);\n"
"")
        GloPel2017.setAnimated(True)
        GloPel2017.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(GloPel2017)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 209, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: rgb(190, 209, 240);\n"
"border-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 9, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(460, 125))
        self.frame_2.setMaximumSize(QtCore.QSize(460, 125))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("\n"
"background-color: rgb(165, 181, 209);\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.labeldistances_11 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_11.setGeometry(QtCore.QRect(205, 4, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labeldistances_11.setFont(font)
        self.labeldistances_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labeldistances_11.setObjectName("labeldistances_11")
        self.Loadbuttonset1 = QtWidgets.QPushButton(self.frame_2)
        self.Loadbuttonset1.setGeometry(QtCore.QRect(60, 7, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Loadbuttonset1.setFont(font)
        self.Loadbuttonset1.setAutoFillBackground(False)
        self.Loadbuttonset1.setStyleSheet("background-color:rgb(188, 198, 207)")
        self.Loadbuttonset1.setObjectName("Loadbuttonset1")
        self.labeldistances_19 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_19.setGeometry(QtCore.QRect(335, 65, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_19.setFont(font)
        self.labeldistances_19.setObjectName("labeldistances_19")
        self.labeldistances_9 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_9.setGeometry(QtCore.QRect(430, 85, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_9.setFont(font)
        self.labeldistances_9.setObjectName("labeldistances_9")
        self.Timescaleset1 = QtWidgets.QLineEdit(self.frame_2)
        self.Timescaleset1.setGeometry(QtCore.QRect(10, 85, 34, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Timescaleset1.setFont(font)
        self.Timescaleset1.setToolTip("")
        self.Timescaleset1.setToolTipDuration(-1)
        self.Timescaleset1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Timescaleset1.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Timescaleset1.setText("")
        self.Timescaleset1.setReadOnly(True)
        self.Timescaleset1.setObjectName("Timescaleset1")
        self.Enableset2 = QtWidgets.QRadioButton(self.frame_2)
        self.Enableset2.setGeometry(QtCore.QRect(325, 45, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Enableset2.setFont(font)
        self.Enableset2.setCheckable(True)
        self.Enableset2.setChecked(False)
        self.Enableset2.setAutoExclusive(True)
        self.Enableset2.setObjectName("Enableset2")
        self.Enableset1 = QtWidgets.QRadioButton(self.frame_2)
        self.Enableset1.setGeometry(QtCore.QRect(10, 45, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Enableset1.setFont(font)
        self.Enableset1.setCheckable(True)
        self.Enableset1.setChecked(True)
        self.Enableset1.setAutoExclusive(True)
        self.Enableset1.setObjectName("Enableset1")
        self.labeldistances_20 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_20.setGeometry(QtCore.QRect(10, 65, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_20.setFont(font)
        self.labeldistances_20.setObjectName("labeldistances_20")
        self.labeldistances_12 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_12.setGeometry(QtCore.QRect(50, 85, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_12.setFont(font)
        self.labeldistances_12.setObjectName("labeldistances_12")
        self.Timescaleset2 = QtWidgets.QLineEdit(self.frame_2)
        self.Timescaleset2.setGeometry(QtCore.QRect(390, 85, 34, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Timescaleset2.setFont(font)
        self.Timescaleset2.setToolTip("")
        self.Timescaleset2.setToolTipDuration(-1)
        self.Timescaleset2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Timescaleset2.setText("")
        self.Timescaleset2.setReadOnly(True)
        self.Timescaleset2.setObjectName("Timescaleset2")
        self.labeldistances_21 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_21.setGeometry(QtCore.QRect(10, 7, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances_21.setFont(font)
        self.labeldistances_21.setObjectName("labeldistances_21")
        self.labeldistances_22 = QtWidgets.QLabel(self.frame_2)
        self.labeldistances_22.setGeometry(QtCore.QRect(335, 7, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labeldistances_22.setFont(font)
        self.labeldistances_22.setObjectName("labeldistances_22")
        self.Loadbuttonset2 = QtWidgets.QPushButton(self.frame_2)
        self.Loadbuttonset2.setGeometry(QtCore.QRect(383, 7, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Loadbuttonset2.setFont(font)
        self.Loadbuttonset2.setAutoFillBackground(False)
        self.Loadbuttonset2.setStyleSheet("background-color:rgb(188, 198, 207)")
        self.Loadbuttonset2.setObjectName("Loadbuttonset2")
        self.Label_first_paramset = QtWidgets.QLabel(self.frame_2)
        self.Label_first_paramset.setGeometry(QtCore.QRect(10, 30, 190, 10))
        self.Label_first_paramset.setMinimumSize(QtCore.QSize(190, 0))
        self.Label_first_paramset.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_first_paramset.setFont(font)
        self.Label_first_paramset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_first_paramset.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Label_first_paramset.setText("")
        self.Label_first_paramset.setObjectName("Label_first_paramset")
        self.Label_fsecond_paramset = QtWidgets.QLabel(self.frame_2)
        self.Label_fsecond_paramset.setGeometry(QtCore.QRect(260, 30, 190, 10))
        self.Label_fsecond_paramset.setMinimumSize(QtCore.QSize(190, 0))
        self.Label_fsecond_paramset.setMaximumSize(QtCore.QSize(190, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_fsecond_paramset.setFont(font)
        self.Label_fsecond_paramset.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_fsecond_paramset.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Label_fsecond_paramset.setText("")
        self.Label_fsecond_paramset.setObjectName("Label_fsecond_paramset")
        self.dual_display_button = QtWidgets.QRadioButton(self.frame_2)
        self.dual_display_button.setGeometry(QtCore.QRect(190, 80, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dual_display_button.setFont(font)
        self.dual_display_button.setAutoFillBackground(False)
        self.dual_display_button.setStyleSheet("selection-color: rgb(255, 0, 0)\n"
"")
        self.dual_display_button.setAutoExclusive(False)
        self.dual_display_button.setObjectName("dual_display_button")
        self.gridLayout_4.addWidget(self.frame_2, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(515, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 10, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 177, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem2, 6, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 127, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(460, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(460, 800))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(165, 181, 209);\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setContentsMargins(3, 3, 3, 5)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.labeldistances_23 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.labeldistances_23.setFont(font)
        self.labeldistances_23.setObjectName("labeldistances_23")
        self.gridLayout.addWidget(self.labeldistances_23, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(220, 15))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(470, 800))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 2)
        self.gridLayout_4.addWidget(self.frame_3, 9, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(460, 178))
        self.frame_4.setMaximumSize(QtCore.QSize(460, 178))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame_4.setFont(font)
        self.frame_4.setStyleSheet("background-color: rgb(165, 181, 209);\n"
"border-color: rgb(255, 0, 0);\n"
"\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setMidLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.labeldistances_30 = QtWidgets.QLabel(self.frame_4)
        self.labeldistances_30.setGeometry(QtCore.QRect(200, 4, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labeldistances_30.setFont(font)
        self.labeldistances_30.setObjectName("labeldistances_30")
        self.DTSVDbutton = QtWidgets.QRadioButton(self.frame_4)
        self.DTSVDbutton.setGeometry(QtCore.QRect(10, 50, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DTSVDbutton.setFont(font)
        self.DTSVDbutton.setChecked(False)
        self.DTSVDbutton.setObjectName("DTSVDbutton")
        self.Maximum_Entropy_But = QtWidgets.QRadioButton(self.frame_4)
        self.Maximum_Entropy_But.setGeometry(QtCore.QRect(10, 70, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Maximum_Entropy_But.setFont(font)
        self.Maximum_Entropy_But.setObjectName("Maximum_Entropy_But")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Simplexbutton = QtWidgets.QRadioButton(self.frame_4)
        self.Simplexbutton.setGeometry(QtCore.QRect(230, 50, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Simplexbutton.setFont(font)
        self.Simplexbutton.setStyleSheet("")
        self.Simplexbutton.setObjectName("Simplexbutton")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.thikonovbutton = QtWidgets.QRadioButton(self.frame_4)
        self.thikonovbutton.setGeometry(QtCore.QRect(10, 30, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.thikonovbutton.setFont(font)
        self.thikonovbutton.setAutoFillBackground(False)
        self.thikonovbutton.setStyleSheet("")
        self.thikonovbutton.setChecked(True)
        self.thikonovbutton.setObjectName("thikonovbutton")
        self.TR_Rbutton = QtWidgets.QRadioButton(self.frame_4)
        self.TR_Rbutton.setGeometry(QtCore.QRect(230, 30, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TR_Rbutton.setFont(font)
        self.TR_Rbutton.setChecked(False)
        self.TR_Rbutton.setObjectName("TR_Rbutton")
        self.StochsticTRbutton = QtWidgets.QRadioButton(self.frame_4)
        self.StochsticTRbutton.setGeometry(QtCore.QRect(340, 30, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StochsticTRbutton.setFont(font)
        self.StochsticTRbutton.setObjectName("StochsticTRbutton")
        self.StartbuttonAna = QtWidgets.QPushButton(self.frame_4)
        self.StartbuttonAna.setGeometry(QtCore.QRect(370, 150, 85, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StartbuttonAna.setFont(font)
        self.StartbuttonAna.setAutoFillBackground(False)
        self.StartbuttonAna.setStyleSheet("background-color:rgb(188, 198, 207)")
        self.StartbuttonAna.setObjectName("StartbuttonAna")
        self.GlobalAnalysis = QtWidgets.QCheckBox(self.frame_4)
        self.GlobalAnalysis.setGeometry(QtCore.QRect(250, 150, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.GlobalAnalysis.setFont(font)
        self.GlobalAnalysis.setToolTip("")
        self.GlobalAnalysis.setToolTipDuration(-1)
        self.GlobalAnalysis.setObjectName("GlobalAnalysis")
        self.CG_Button = QtWidgets.QRadioButton(self.frame_4)
        self.CG_Button.setGeometry(QtCore.QRect(340, 50, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CG_Button.setFont(font)
        self.CG_Button.setObjectName("CG_Button")
        self.Powell = QtWidgets.QRadioButton(self.frame_4)
        self.Powell.setGeometry(QtCore.QRect(340, 70, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Powell.setFont(font)
        self.Powell.setObjectName("Powell")
        self.line = QtWidgets.QFrame(self.frame_4)
        self.line.setGeometry(QtCore.QRect(5, 138, 451, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line.setFont(font)
        self.line.setStyleSheet("gridline-color: rgb(255, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labeldistances_14 = QtWidgets.QLabel(self.frame_4)
        self.labeldistances_14.setGeometry(QtCore.QRect(15, 94, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_14.setFont(font)
        self.labeldistances_14.setObjectName("labeldistances_14")
        self.L_Curve_numberBox = QtWidgets.QSpinBox(self.frame_4)
        self.L_Curve_numberBox.setEnabled(True)
        self.L_Curve_numberBox.setGeometry(QtCore.QRect(120, 92, 41, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.L_Curve_numberBox.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.L_Curve_numberBox.setFont(font)
        self.L_Curve_numberBox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.L_Curve_numberBox.setReadOnly(False)
        self.L_Curve_numberBox.setMinimum(1)
        self.L_Curve_numberBox.setMaximum(20)
        self.L_Curve_numberBox.setSingleStep(1)
        self.L_Curve_numberBox.setProperty("value", 5)
        self.L_Curve_numberBox.setObjectName("L_Curve_numberBox")
        self.line_2 = QtWidgets.QFrame(self.frame_4)
        self.line_2.setGeometry(QtCore.QRect(210, 30, 16, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_2.setFont(font)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet("color: rgb(170, 0, 0);\n"
"")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.DiffEvolv_Button = QtWidgets.QRadioButton(self.frame_4)
        self.DiffEvolv_Button.setGeometry(QtCore.QRect(230, 70, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.DiffEvolv_Button.setFont(font)
        self.DiffEvolv_Button.setObjectName("DiffEvolv_Button")
        self.use_adaptive_kernel = QtWidgets.QCheckBox(self.frame_4)
        self.use_adaptive_kernel.setGeometry(QtCore.QRect(10, 120, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.use_adaptive_kernel.setFont(font)
        self.use_adaptive_kernel.setToolTip("")
        self.use_adaptive_kernel.setToolTipDuration(-1)
        self.use_adaptive_kernel.setObjectName("use_adaptive_kernel")
        self.use_large_kernel = QtWidgets.QCheckBox(self.frame_4)
        self.use_large_kernel.setGeometry(QtCore.QRect(120, 120, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.use_large_kernel.setFont(font)
        self.use_large_kernel.setToolTip("")
        self.use_large_kernel.setToolTipDuration(-1)
        self.use_large_kernel.setObjectName("use_large_kernel")
        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setGeometry(QtCore.QRect(210, 30, 16, 101))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_4.setFont(font)
        self.line_4.setAutoFillBackground(False)
        self.line_4.setStyleSheet("color: rgb(170, 0, 0);\n"
"")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(1)
        self.line_4.setMidLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.Multigaussian_Box = QtWidgets.QCheckBox(self.frame_4)
        self.Multigaussian_Box.setGeometry(QtCore.QRect(270, 110, 101, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Multigaussian_Box.setFont(font)
        self.Multigaussian_Box.setChecked(False)
        self.Multigaussian_Box.setAutoExclusive(False)
        self.Multigaussian_Box.setObjectName("Multigaussian_Box")
        self.line.raise_()
        self.labeldistances_30.raise_()
        self.DTSVDbutton.raise_()
        self.Maximum_Entropy_But.raise_()
        self.label.raise_()
        self.Simplexbutton.raise_()
        self.label_2.raise_()
        self.thikonovbutton.raise_()
        self.TR_Rbutton.raise_()
        self.StochsticTRbutton.raise_()
        self.StartbuttonAna.raise_()
        self.GlobalAnalysis.raise_()
        self.CG_Button.raise_()
        self.Powell.raise_()
        self.labeldistances_14.raise_()
        self.L_Curve_numberBox.raise_()
        self.line_2.raise_()
        self.DiffEvolv_Button.raise_()
        self.use_adaptive_kernel.raise_()
        self.use_large_kernel.raise_()
        self.line_4.raise_()
        self.Multigaussian_Box.raise_()
        self.gridLayout_4.addWidget(self.frame_4, 6, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Plotdist1 = QtWidgets.QWidget(self.centralwidget)
        self.Plotdist1.setMinimumSize(QtCore.QSize(200, 200))
        self.Plotdist1.setObjectName("Plotdist1")
        self.gridLayout_2.addWidget(self.Plotdist1, 2, 0, 1, 2)
        self.ZoomFTScrollBar_3 = QtWidgets.QScrollBar(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ZoomFTScrollBar_3.setFont(font)
        self.ZoomFTScrollBar_3.setStyleSheet("background-color: rgb(165, 181, 209);")
        self.ZoomFTScrollBar_3.setMaximum(5)
        self.ZoomFTScrollBar_3.setPageStep(5)
        self.ZoomFTScrollBar_3.setProperty("value", 5)
        self.ZoomFTScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomFTScrollBar_3.setObjectName("ZoomFTScrollBar_3")
        self.gridLayout_2.addWidget(self.ZoomFTScrollBar_3, 3, 0, 1, 1)
        self.ZoomFTScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ZoomFTScrollBar.setFont(font)
        self.ZoomFTScrollBar.setStyleSheet("background-color: rgb(165, 181, 209);")
        self.ZoomFTScrollBar.setMaximum(10)
        self.ZoomFTScrollBar.setProperty("value", 3)
        self.ZoomFTScrollBar.setSliderPosition(3)
        self.ZoomFTScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomFTScrollBar.setObjectName("ZoomFTScrollBar")
        self.gridLayout_2.addWidget(self.ZoomFTScrollBar, 3, 2, 1, 1)
        self.Plotdist2 = QtWidgets.QWidget(self.centralwidget)
        self.Plotdist2.setMinimumSize(QtCore.QSize(160, 200))
        self.Plotdist2.setBaseSize(QtCore.QSize(150, 150))
        self.Plotdist2.setObjectName("Plotdist2")
        self.gridLayout_2.addWidget(self.Plotdist2, 2, 2, 1, 2)
        self.Detach_resiuals = QtWidgets.QPushButton(self.centralwidget)
        self.Detach_resiuals.setMinimumSize(QtCore.QSize(100, 14))
        self.Detach_resiuals.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Detach_resiuals.setFont(font)
        self.Detach_resiuals.setToolTip("")
        self.Detach_resiuals.setToolTipDuration(-1)
        self.Detach_resiuals.setObjectName("Detach_resiuals")
        self.gridLayout_2.addWidget(self.Detach_resiuals, 1, 3, 1, 1)
        self.ZoomFTScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZoomFTScrollBar_2.sizePolicy().hasHeightForWidth())
        self.ZoomFTScrollBar_2.setSizePolicy(sizePolicy)
        self.ZoomFTScrollBar_2.setMinimumSize(QtCore.QSize(0, 14))
        self.ZoomFTScrollBar_2.setMaximumSize(QtCore.QSize(16777215, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ZoomFTScrollBar_2.setFont(font)
        self.ZoomFTScrollBar_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ZoomFTScrollBar_2.setStyleSheet("background-color: rgb(165, 181, 209);")
        self.ZoomFTScrollBar_2.setMaximum(5)
        self.ZoomFTScrollBar_2.setPageStep(5)
        self.ZoomFTScrollBar_2.setProperty("value", 5)
        self.ZoomFTScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.ZoomFTScrollBar_2.setObjectName("ZoomFTScrollBar_2")
        self.gridLayout_2.addWidget(self.ZoomFTScrollBar_2, 1, 0, 1, 2)
        self.Enable_validation_button = QtWidgets.QPushButton(self.centralwidget)
        self.Enable_validation_button.setMinimumSize(QtCore.QSize(100, 14))
        self.Enable_validation_button.setMaximumSize(QtCore.QSize(16777215, 14))
        self.Enable_validation_button.setSizeIncrement(QtCore.QSize(0, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Enable_validation_button.setFont(font)
        self.Enable_validation_button.setToolTip("")
        self.Enable_validation_button.setToolTipDuration(-1)
        self.Enable_validation_button.setObjectName("Enable_validation_button")
        self.gridLayout_2.addWidget(self.Enable_validation_button, 1, 2, 1, 1)
        self.L_curve_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.L_curve_button.sizePolicy().hasHeightForWidth())
        self.L_curve_button.setSizePolicy(sizePolicy)
        self.L_curve_button.setMinimumSize(QtCore.QSize(120, 14))
        self.L_curve_button.setMaximumSize(QtCore.QSize(120, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.L_curve_button.setFont(font)
        self.L_curve_button.setToolTip("")
        self.L_curve_button.setToolTipDuration(-1)
        self.L_curve_button.setObjectName("L_curve_button")
        self.gridLayout_2.addWidget(self.L_curve_button, 3, 3, 1, 1)
        self.Maximum_area_norm_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Maximum_area_norm_button.sizePolicy().hasHeightForWidth())
        self.Maximum_area_norm_button.setSizePolicy(sizePolicy)
        self.Maximum_area_norm_button.setMinimumSize(QtCore.QSize(121, 14))
        self.Maximum_area_norm_button.setMaximumSize(QtCore.QSize(121, 14))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Maximum_area_norm_button.setFont(font)
        self.Maximum_area_norm_button.setObjectName("Maximum_area_norm_button")
        self.gridLayout_2.addWidget(self.Maximum_area_norm_button, 3, 1, 1, 1)
        self.PlotTT1 = QtWidgets.QWidget(self.centralwidget)
        self.PlotTT1.setEnabled(True)
        self.PlotTT1.setMinimumSize(QtCore.QSize(360, 190))
        self.PlotTT1.setObjectName("PlotTT1")
        self.gridLayout_2.addWidget(self.PlotTT1, 0, 0, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 10, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Savebutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Savebutton.sizePolicy().hasHeightForWidth())
        self.Savebutton.setSizePolicy(sizePolicy)
        self.Savebutton.setMinimumSize(QtCore.QSize(0, 20))
        self.Savebutton.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Savebutton.setFont(font)
        self.Savebutton.setAutoFillBackground(False)
        self.Savebutton.setStyleSheet("background-color:rgb(188, 198, 207)")
        self.Savebutton.setObjectName("Savebutton")
        self.buttonGroup = QtWidgets.QButtonGroup(GloPel2017)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Savebutton)
        self.gridLayout_3.addWidget(self.Savebutton, 0, 0, 1, 1)
        self.Closebutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Closebutton.sizePolicy().hasHeightForWidth())
        self.Closebutton.setSizePolicy(sizePolicy)
        self.Closebutton.setMinimumSize(QtCore.QSize(0, 20))
        self.Closebutton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Closebutton.setSizeIncrement(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Closebutton.setFont(font)
        self.Closebutton.setAutoFillBackground(False)
        self.Closebutton.setStyleSheet("background-color:rgb(188, 198, 207)")
        self.Closebutton.setObjectName("Closebutton")
        self.buttonGroup.addButton(self.Closebutton)
        self.gridLayout_3.addWidget(self.Closebutton, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 10, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 137, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 3, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(460, 138))
        self.frame.setMaximumSize(QtCore.QSize(460, 138))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(165, 181, 209);\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.labeldistances_29 = QtWidgets.QLabel(self.frame)
        self.labeldistances_29.setGeometry(QtCore.QRect(195, 4, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.labeldistances_29.setFont(font)
        self.labeldistances_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labeldistances_29.setObjectName("labeldistances_29")
        self.labeldistances_16 = QtWidgets.QLabel(self.frame)
        self.labeldistances_16.setGeometry(QtCore.QRect(10, 20, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_16.setFont(font)
        self.labeldistances_16.setObjectName("labeldistances_16")
        self.labeldistances_17 = QtWidgets.QLabel(self.frame)
        self.labeldistances_17.setGeometry(QtCore.QRect(10, 62, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_17.setFont(font)
        self.labeldistances_17.setObjectName("labeldistances_17")
        self.labeldistances_6 = QtWidgets.QLabel(self.frame)
        self.labeldistances_6.setGeometry(QtCore.QRect(57, 83, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_6.setFont(font)
        self.labeldistances_6.setObjectName("labeldistances_6")
        self.labeldistances_7 = QtWidgets.QLabel(self.frame)
        self.labeldistances_7.setGeometry(QtCore.QRect(77, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_7.setFont(font)
        self.labeldistances_7.setObjectName("labeldistances_7")
        self.labeldistances_24 = QtWidgets.QLabel(self.frame)
        self.labeldistances_24.setGeometry(QtCore.QRect(360, 20, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_24.setFont(font)
        self.labeldistances_24.setObjectName("labeldistances_24")
        self.labeldistances_13 = QtWidgets.QLabel(self.frame)
        self.labeldistances_13.setGeometry(QtCore.QRect(440, 40, 10, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldistances_13.setFont(font)
        self.labeldistances_13.setObjectName("labeldistances_13")
        self.AutomaticPc0order = QtWidgets.QLineEdit(self.frame)
        self.AutomaticPc0order.setGeometry(QtCore.QRect(400, 38, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.AutomaticPc0order.setFont(font)
        self.AutomaticPc0order.setStyleSheet("background-color:rgb(185, 185, 185)")
        self.AutomaticPc0order.setReadOnly(True)
        self.AutomaticPc0order.setObjectName("AutomaticPc0order")
        self.labeldistances_26 = QtWidgets.QLabel(self.frame)
        self.labeldistances_26.setGeometry(QtCore.QRect(360, 38, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_26.setFont(font)
        self.labeldistances_26.setObjectName("labeldistances_26")
        self.labeldistances_28 = QtWidgets.QLabel(self.frame)
        self.labeldistances_28.setGeometry(QtCore.QRect(106, 62, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_28.setFont(font)
        self.labeldistances_28.setObjectName("labeldistances_28")
        self.Nomalizebox = QtWidgets.QSpinBox(self.frame)
        self.Nomalizebox.setEnabled(True)
        self.Nomalizebox.setGeometry(QtCore.QRect(106, 80, 45, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Nomalizebox.setFont(font)
        self.Nomalizebox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Nomalizebox.setReadOnly(False)
        self.Nomalizebox.setMinimum(-200)
        self.Nomalizebox.setMaximum(2000)
        self.Nomalizebox.setProperty("value", 0)
        self.Nomalizebox.setDisplayIntegerBase(10)
        self.Nomalizebox.setObjectName("Nomalizebox")
        self.labeldistances_31 = QtWidgets.QLabel(self.frame)
        self.labeldistances_31.setGeometry(QtCore.QRect(156, 83, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_31.setFont(font)
        self.labeldistances_31.setObjectName("labeldistances_31")
        self.labeldistances_32 = QtWidgets.QLabel(self.frame)
        self.labeldistances_32.setGeometry(QtCore.QRect(170, 78, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(False)
        self.labeldistances_32.setFont(font)
        self.labeldistances_32.setObjectName("labeldistances_32")
        self.Bg_Start = QtWidgets.QSpinBox(self.frame)
        self.Bg_Start.setGeometry(QtCore.QRect(10, 38, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Bg_Start.setFont(font)
        self.Bg_Start.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Bg_Start.setKeyboardTracking(True)
        self.Bg_Start.setMaximum(10000)
        self.Bg_Start.setSingleStep(8)
        self.Bg_Start.setObjectName("Bg_Start")
        self.show_imaginary = QtWidgets.QRadioButton(self.frame)
        self.show_imaginary.setGeometry(QtCore.QRect(10, 111, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.show_imaginary.setFont(font)
        self.show_imaginary.setAutoFillBackground(False)
        self.show_imaginary.setStyleSheet("selection-color: rgb(255, 0, 0);\n"
"")
        self.show_imaginary.setObjectName("show_imaginary")
        self.Checkbox_GlobalBg = QtWidgets.QCheckBox(self.frame)
        self.Checkbox_GlobalBg.setGeometry(QtCore.QRect(305, 111, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Checkbox_GlobalBg.setFont(font)
        self.Checkbox_GlobalBg.setObjectName("Checkbox_GlobalBg")
        self.Zerotimebox = QtWidgets.QSpinBox(self.frame)
        self.Zerotimebox.setGeometry(QtCore.QRect(10, 80, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Zerotimebox.setFont(font)
        self.Zerotimebox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Zerotimebox.setMinimum(-100000)
        self.Zerotimebox.setMaximum(100000)
        self.Zerotimebox.setSingleStep(4)
        self.Zerotimebox.setObjectName("Zerotimebox")
        self.Checkbox_Moddepth_norm = QtWidgets.QCheckBox(self.frame)
        self.Checkbox_Moddepth_norm.setGeometry(QtCore.QRect(150, 111, 151, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Checkbox_Moddepth_norm.setFont(font)
        self.Checkbox_Moddepth_norm.setObjectName("Checkbox_Moddepth_norm")
        self.labeldistances_33 = QtWidgets.QLabel(self.frame)
        self.labeldistances_33.setGeometry(QtCore.QRect(106, 20, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_33.setFont(font)
        self.labeldistances_33.setObjectName("labeldistances_33")
        self.Bg_excluded_vol = QtWidgets.QSpinBox(self.frame)
        self.Bg_excluded_vol.setEnabled(True)
        self.Bg_excluded_vol.setGeometry(QtCore.QRect(275, 38, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Bg_excluded_vol.setFont(font)
        self.Bg_excluded_vol.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Bg_excluded_vol.setReadOnly(False)
        self.Bg_excluded_vol.setMinimum(0)
        self.Bg_excluded_vol.setMaximum(15)
        self.Bg_excluded_vol.setProperty("value", 0)
        self.Bg_excluded_vol.setDisplayIntegerBase(10)
        self.Bg_excluded_vol.setObjectName("Bg_excluded_vol")
        self.labeldistances_34 = QtWidgets.QLabel(self.frame)
        self.labeldistances_34.setGeometry(QtCore.QRect(275, 20, 74, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_34.setFont(font)
        self.labeldistances_34.setObjectName("labeldistances_34")
        self.labeldistances_8 = QtWidgets.QLabel(self.frame)
        self.labeldistances_8.setGeometry(QtCore.QRect(324, 40, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_8.setFont(font)
        self.labeldistances_8.setObjectName("labeldistances_8")
        self.Excluded_volBox = QtWidgets.QCheckBox(self.frame)
        self.Excluded_volBox.setGeometry(QtCore.QRect(370, 76, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Excluded_volBox.setFont(font)
        self.Excluded_volBox.setObjectName("Excluded_volBox")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(5, 101, 441, 12))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_3.setFont(font)
        self.line_3.setStyleSheet("gridline-color: rgb(255, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Cutoffbox = QtWidgets.QSpinBox(self.frame)
        self.Cutoffbox.setGeometry(QtCore.QRect(190, 38, 60, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Cutoffbox.setFont(font)
        self.Cutoffbox.setToolTip("")
        self.Cutoffbox.setToolTipDuration(-1)
        self.Cutoffbox.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.Cutoffbox.setMinimum(-100000)
        self.Cutoffbox.setMaximum(100000)
        self.Cutoffbox.setSingleStep(4)
        self.Cutoffbox.setObjectName("Cutoffbox")
        self.labeldistances_35 = QtWidgets.QLabel(self.frame)
        self.labeldistances_35.setGeometry(QtCore.QRect(190, 20, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_35.setFont(font)
        self.labeldistances_35.setObjectName("labeldistances_35")
        self.labeldistances_10 = QtWidgets.QLabel(self.frame)
        self.labeldistances_10.setGeometry(QtCore.QRect(254, 40, 18, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.labeldistances_10.setFont(font)
        self.labeldistances_10.setObjectName("labeldistances_10")
        self.Bg_dimension = QtWidgets.QDoubleSpinBox(self.frame)
        self.Bg_dimension.setGeometry(QtCore.QRect(106, 38, 54, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Bg_dimension.setFont(font)
        self.Bg_dimension.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Bg_dimension.setDecimals(1)
        self.Bg_dimension.setMinimum(1.0)
        self.Bg_dimension.setMaximum(6.0)
        self.Bg_dimension.setSingleStep(0.1)
        self.Bg_dimension.setProperty("value", 3.0)
        self.Bg_dimension.setObjectName("Bg_dimension")
        self.Fit_Background_dimension = QtWidgets.QCheckBox(self.frame)
        self.Fit_Background_dimension.setGeometry(QtCore.QRect(280, 76, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Fit_Background_dimension.setFont(font)
        self.Fit_Background_dimension.setObjectName("Fit_Background_dimension")
        self.Form_factor_based_fit = QtWidgets.QCheckBox(self.frame)
        self.Form_factor_based_fit.setGeometry(QtCore.QRect(188, 77, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.Form_factor_based_fit.setFont(font)
        self.Form_factor_based_fit.setObjectName("Form_factor_based_fit")
        self.gridLayout_4.addWidget(self.frame, 3, 1, 1, 1)
        GloPel2017.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GloPel2017)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 926, 25))
        self.menubar.setMaximumSize(QtCore.QSize(1000, 1000))
        self.menubar.setObjectName("menubar")
        GloPel2017.setMenuBar(self.menubar)
        self.action_Load_Manual = QtWidgets.QAction(GloPel2017)
        self.action_Load_Manual.setObjectName("action_Load_Manual")
        self.actionEnable_Tooltip = QtWidgets.QAction(GloPel2017)
        self.actionEnable_Tooltip.setObjectName("actionEnable_Tooltip")

        self.retranslateUi(GloPel2017)
        QtCore.QMetaObject.connectSlotsByName(GloPel2017)

    def retranslateUi(self, GloPel2017):
        _translate = QtCore.QCoreApplication.translate
        GloPel2017.setWindowTitle(_translate("GloPel2017", "GloPel:  Global Analysis of PELDOR Data"))
        self.labeldistances_11.setText(_translate("GloPel2017", "Data Input"))
        self.Loadbuttonset1.setText(_translate("GloPel2017", "Load"))
        self.labeldistances_19.setText(_translate("GloPel2017", "Stepsize dataset 2"))
        self.labeldistances_9.setText(_translate("GloPel2017", "ns"))
        self.Enableset2.setText(_translate("GloPel2017", "Enab&le dataset 2"))
        self.Enableset1.setText(_translate("GloPel2017", "Enable dataset &1"))
        self.labeldistances_20.setText(_translate("GloPel2017", "Stepsize dataset 1"))
        self.labeldistances_12.setText(_translate("GloPel2017", "ns"))
        self.labeldistances_21.setText(_translate("GloPel2017", "Set1"))
        self.labeldistances_22.setText(_translate("GloPel2017", "Set2"))
        self.Loadbuttonset2.setText(_translate("GloPel2017", "Load"))
        self.dual_display_button.setText(_translate("GloPel2017", "D&ual display"))
        self.labeldistances_23.setText(_translate("GloPel2017", "Log:"))
        self.labeldistances_30.setText(_translate("GloPel2017", "Analysis"))
        self.DTSVDbutton.setText(_translate("GloPel2017", "Tikhonov &1. Order"))
        self.Maximum_Entropy_But.setText(_translate("GloPel2017", "&Hybrid Functional"))
        self.label.setText(_translate("GloPel2017", "Regularization"))
        self.Simplexbutton.setText(_translate("GloPel2017", "SLS&QP"))
        self.label_2.setText(_translate("GloPel2017", "Fitting"))
        self.thikonovbutton.setText(_translate("GloPel2017", "Tikhonov &2. Order"))
        self.TR_Rbutton.setText(_translate("GloPel2017", "&Trust-region"))
        self.StochsticTRbutton.setText(_translate("GloPel2017", "Stochastic/TR"))
        self.StartbuttonAna.setText(_translate("GloPel2017", "Start"))
        self.GlobalAnalysis.setText(_translate("GloPel2017", "Global analysis"))
        self.CG_Button.setText(_translate("GloPel2017", "BFGS"))
        self.Powell.setText(_translate("GloPel2017", "&Powell"))
        self.labeldistances_14.setText(_translate("GloPel2017", "L-Curve number"))
        self.DiffEvolv_Button.setText(_translate("GloPel2017", "&COBYLA"))
        self.use_adaptive_kernel.setText(_translate("GloPel2017", "Med.-size kernel"))
        self.use_large_kernel.setText(_translate("GloPel2017", "Large kernel"))
        self.Multigaussian_Box.setText(_translate("GloPel2017", "Enable Fitting"))
        self.Detach_resiuals.setText(_translate("GloPel2017", "Residual inspection"))
        self.Enable_validation_button.setText(_translate("GloPel2017", "Tikhonov validation"))
        self.L_curve_button.setText(_translate("GloPel2017", "L-Curve / Cor.-Curve"))
        self.Maximum_area_norm_button.setText(_translate("GloPel2017", "Maximum/ Area "))
        self.Savebutton.setText(_translate("GloPel2017", "Save"))
        self.Closebutton.setText(_translate("GloPel2017", "Exit"))
        self.labeldistances_29.setText(_translate("GloPel2017", "Preprocessing"))
        self.labeldistances_16.setText(_translate("GloPel2017", "Bg. start"))
        self.labeldistances_17.setText(_translate("GloPel2017", "Zerotime"))
        self.labeldistances_6.setText(_translate("GloPel2017", "ns"))
        self.labeldistances_7.setText(_translate("GloPel2017", "ns"))
        self.labeldistances_24.setText(_translate("GloPel2017", "Automatic PC"))
        self.labeldistances_13.setText(_translate("GloPel2017", "°"))
        self.AutomaticPc0order.setText(_translate("GloPel2017", "0"))
        self.labeldistances_26.setText(_translate("GloPel2017", "0. Ord"))
        self.labeldistances_28.setText(_translate("GloPel2017", "Man. norm."))
        self.labeldistances_31.setText(_translate("GloPel2017", "10"))
        self.labeldistances_32.setText(_translate("GloPel2017", "-3"))
        self.show_imaginary.setText(_translate("GloPel2017", "Show imaginary"))
        self.Checkbox_GlobalBg.setText(_translate("GloPel2017", "Global BG correction"))
        self.Checkbox_Moddepth_norm.setText(_translate("GloPel2017", "Mod. depth normaliz."))
        self.labeldistances_33.setText(_translate("GloPel2017", "Bg. dimension"))
        self.labeldistances_34.setText(_translate("GloPel2017", "Excluded vol."))
        self.labeldistances_8.setText(_translate("GloPel2017", "nm"))
        self.Excluded_volBox.setText(_translate("GloPel2017", "Use ex. vol."))
        self.labeldistances_35.setText(_translate("GloPel2017", "Cut"))
        self.labeldistances_10.setText(_translate("GloPel2017", "ns"))
        self.Fit_Background_dimension.setText(_translate("GloPel2017", "Fit Bg. dim"))
        self.Form_factor_based_fit.setText(_translate("GloPel2017", "Form fac. fit"))
        self.action_Load_Manual.setText(_translate("GloPel2017", "&Load Manual"))
        self.actionEnable_Tooltip.setText(_translate("GloPel2017", "Enable Tooltip"))

