#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This file was generated by Alchemist - Automated build system based on Buildbot.
It is intended for propagation of build information back to the original project.
"""

__bauthor__ = "Alchemist - Automated build system based on Buildbot"
__brevision__ = "f7141de1124b4b502c018b2cb27a11d9e1227bca"
__bcodename__ = "production"
__bsuite__ = "stable"
__bversion__ = "2.7.13.211"
__bversion_full__ = "2.7.13.211-f7141de1124b4b502c018b2cb27a11d9e1227bca (production-stable)"
__bdate__ = "2020-09-01T13:40:03.001088"