[tool.poetry]
name = "discord-pretty-help"
version = "1.1.0"
description = "And nicer looking interactive help menu for discord.py"
authors = ["StroupBSlayen <29642143+stroupbslayen@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/stroupbslayen/discord-pretty-help"
keywords=["discord", "discord.py", "discord bot"]
packages = [
    {include = "pretty_help"}
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
