build: false
branches:
  only:
    - master
    - test
environment:
  matrix:
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python37"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - "%PYTHON%/python.exe -m pip install -U pip setuptools"

  - "%PYTHON%/Scripts/pip.exe install ."
  - "%PYTHON%/Scripts/pip.exe install -r dev_requirements.txt"

test_script:
  - "set path=%PYTHON%/Scripts;%path%"
  - "%PYTHON%/python.exe --version"
  - "%PYTHON%/Scripts/pip.exe --version"
  - "doit pyflakes"
  - "py.test"
