[tool.poetry]
name = "python-awair-local-sensors"
version = "0.2.0"
description = "asyncio client for the Awair GraphQL API"
authors = ["Andrew Hayworth <ahayworth@gmail.com>", "Bobby Powers <bobbypowers@gmail.com"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bpowers/python_awair"
repository = "https://github.com/bpowers/python_awair"
keywords = ["awair", "getawair", "api", "async", "asyncio"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "Topic :: Home Automation",
    "Topic :: Software Development :: Libraries",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.6"
aiohttp = "^3.6.2"
voluptuous = "^0.11.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
codecov = "^2.1.9"
coverage = "^5.2.1"
flake8 =  "^3.8.3"
flake8-docstrings =  "^1.5.0"
isort =  "^5.4.2"
mypy =  "^0.782"
pydocstyle =  "^5.1.1"
pylint =  "^2.6.0"
pyls-mypy = { git = "https://github.com/tomv564/pyls-mypy" }
pytest = "^6.0.1"
pytest-aiohttp = "^0.3.0"
pytest-cov = "^2.10.1"
python-language-server =  "^0.34.1"
sphinx =  "^3.2.1"
sphinx-readable-theme =  "^1.3.0"
tox = "^3.19.0"
vcrpy = "^4.1.0"

[tool.poetry.urls]
"Say Thanks" = "https://saythanks.io/to/ahayworth@gmail.com"

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38
isolated_build = True
skipsdist = True
skip_missing_interpreters = True

[testenv]
whitelist_externals = poetry
commands = poetry run pytest {posargs}

[testenv:lint]
whitelist_externals = poetry
commands =
  poetry run black . --check
  poetry run isort --check python_awair/ tests/
  poetry run flake8 python_awair/ tests/
  poetry run pylint python_awair/ tests/
  poetry run mypy python_awair/ tests/

[testenv:coverage]
whitelist_externals =
  poetry
  codecov
passenv = CI CODECOV* GITHUB_ACTION GITHUB_REF GITHUB_REPOSITORY GITHUB_HEAD_REF GITHUB_SHA GITHUB_RUN_ID
commands =
  poetry run pytest --cov=python_awair {posargs}
  codecov
"""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
