[tool.poetry]
name = "pgdiff"
version = "0.1.20-1"
description = ""
authors = ["Your Name <you@example.com>"]
include = ["sql/*.sql", "pgdiff/py.typed"]
packages = [
    { include = "pgdiff" },
]

[tool.poetry.dependencies]
python = "^3.6"
psycopg2 = "^2.8.5"
typing_extensions = "^3.7.4"
click = "^7.0"
networkx = "^2.4"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
mypy = ">=0.770"
pylint = "^2.5.3"

[tool.poetry.scripts]
pgdiff = "pgdiff.cli:cli"

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "bad-continuation",
    "invalid-name",
    "unused-argument",
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
