[tool.poetry]
name = "yellowbox"
version = "0.1.0a"
description = ""
authors = ["biocatch ltd"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/biocatchltd/yellowbox"

[tool.poetry.dependencies]
python = "^3.7"
docker = "^4.2.0"
yaspin = "^1.0.0"

redis = {version="*", optional=true}
pika = {version="*", optional=true}
kafka-python = {version="*", optional=true}
azure-storage-blob = { version = "^12.0.0", optional = true }
cffi = {version = "^1.14.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-cov = "^2.10"
requests = "^2"
flake8 = "*"
pytype = "*"

[tool.poetry.extras]
redis = ["redis"]
rabbit = ["pika"]
kafka = ["kafka-python"]
azure = ["azure-storage-blob", "cffi"]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
