[tool.poetry]
name = "norwegian_forest_cat"
version = "0.0.5"
description = "A small example package"
authors = ["chiawei chang <williamcw.chang@moxa.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
