
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-04T12:04:00-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2bc7ceb1cd87512cc9210aad58419353fd7256",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
