# Generated by Django 3.1 on 2020-08-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_test',
        ),
    ]
