
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-01T17:47:21+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "39d8dc53be676c965e8b16809ec4e999082fab41",
 "version": "2.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
