[tool.poetry]
name = "lk-utils"
version = "1.4.0"
description = "LK Utils is made for data processing."
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
bs4 = "^0.0.1"
lk-logger = "^3.5"
lxml = "^4.5"
requests = "^2.24"
xlrd = "^1.2"
xlsxwriter = "^1.3"
# csv = "*"
# pdfminer = "*"
# pdfplumber = "*"
# pypinyin = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
