[tool.black]
line-length = 90
target-version = ['py37']
include = '\.pyi?$'

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=90
force_to_top = ['nomnomdata']
default_section = 'THIRDPARTY'
known_first_party = ['nomnomdata', 'nominode', 'nomcom', 'engines_common', 'nomitall']
ensure_newline_before_comments=true

[tool.poetry]
name="nomnomdata-tools-engine"
license="LGPL-3.0-only"
repository="https://gitlab.com/nomnomdata/tools/nomnomdata-tools-engine"
version = "0.12.5.post3.dev0"
description="Package containing tooling for developing nominode engines"
authors=["Nom Nom Data Inc <info@nomnomdata.com>"]
readme="README.md"
packages = [
    { include = "nomnomdata" }
]
include = ["nomnomdata/tools/engine/testpass.out","nomnomdata/tools/engine/template/*"]


[tool.poetry.plugins."nomnomdata.cli_plugins"]
engine-tools="nomnomdata.tools.engine.cli:cli"

[tool.poetry.dependencies]
python = ">=3.7.4, <3.8"
docker = {version = "^4.2.0", extras = ["ssh"]}
pyyaml = "^5.3.1"
docker-compose = "^1.25.5"
jinja2 = "^2.11.2"
cerberus = "^1.3.2"
requests = "^2.23.0"
nomnomdata-cli = "^0.1.0"
fsspec = "^0.7.3"
s3fs = "^0.4.2"
dunamai = "^1.1.0"
nomnomdata-auth = "^2.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
pytest-snapshot = "^0.4.1"
pytest-cov = "^2.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
