# Generated by Django 3.0.5 on 2020-08-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('apiqa_storage', '0006_auto_20200522_0624'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='attachment',
                    index=models.Index(fields=['path'],
                                       name='attachment_path_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE INDEX CONCURRENTLY "attachment_path_idx"
                        ON "apiqa_storage_attachment" ("path");
                        """,
                    reverse_sql="""
                        DROP INDEX "attachment_path_idx"
                        """
                ),
            ]
        )
    ]
