# Generated by Django 3.0.5 on 2020-08-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiqa_storage', '0007_auto_20200803_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='linked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apiqa_storage.Attachment'),
        ),
    ]
