
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-07T01:04:31+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba5f74b53a33bc277bad77fb1931a12c7f98b6d0",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
