# coding: utf-8

"""
    Aliro Quantum App

    This is an api for the Aliro Quantum App  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aliro_quantum
from aliro_quantum.api.device_details_api import DeviceDetailsApi  # noqa: E501
from aliro_quantum.rest import ApiException


class TestDeviceDetailsApi(unittest.TestCase):
    """DeviceDetailsApi unit test stubs"""

    def setUp(self):
        self.api = aliro_quantum.api.device_details_api.DeviceDetailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_devices_list_vendors_get(self):
        """Test case for devices_list_vendors_get

        retrieves list of vendors to send as a query param to the devices list call  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
