from derobertis_project_logo.logos.nd import ND
from derobertis_project_logo.project_logo import ProjectLogo
from derobertis_project_logo.logos.triangle import Triangle

_pyexlatex_logo = Triangle()
_pyexlatex_logo.set_color("1", "#9c6ff4")
_pyexlatex_logo.set_color("2", "#8eab89")
_pyexlatex_logo.set_color("3", "#113ae1")
_pyexlatex_logo.set_color("4", "#75b415")
_pyexlatex_logo.set_color("5", "#d68556")
_pyexlatex_logo.set_color("6", "#783b98")
_pyexlatex_logo.set_color("7", "#2233d2")
_pyexlatex_logo.set_color("8", "#a8d887")
_pyexlatex_logo.set_color("9", "#f918c5")
_pyexlatex_logo.set_color("10", "#c0797f")
_pyexlatex_logo.set_color("11", "#5e0558")
_pyexlatex_logo.set_color("12", "#e05bd1")
_pyexlatex_logo.set_color("border", "#000")
pyexlatex_logo = ProjectLogo("pyexlatex", _pyexlatex_logo)

_datacode_logo = Triangle()
_datacode_logo.set_color("1", "#ae3e88")
_datacode_logo.set_color("2", "#184095")
_datacode_logo.set_color("3", "#2d14ab")
_datacode_logo.set_color("4", "#8e22bd")
_datacode_logo.set_color("5", "#66fdb5")
_datacode_logo.set_color("6", "#9d609e")
_datacode_logo.set_color("7", "#0aa4ce")
_datacode_logo.set_color("8", "#d7b185")
_datacode_logo.set_color("9", "#d119aa")
_datacode_logo.set_color("10", "#918feb")
_datacode_logo.set_color("11", "#ea694b")
_datacode_logo.set_color("12", "#4e10e4")
_datacode_logo.set_color("border", "#000")
datacode_logo = ProjectLogo("datacode", _datacode_logo)

_pyfileconf_logo = Triangle()
_pyfileconf_logo.set_color("1", "#25cc59")
_pyfileconf_logo.set_color("2", "#27d3ce")
_pyfileconf_logo.set_color("3", "#349bc0")
_pyfileconf_logo.set_color("4", "#622603")
_pyfileconf_logo.set_color("5", "#fcba32")
_pyfileconf_logo.set_color("6", "#15ada0")
_pyfileconf_logo.set_color("7", "#aefc1b")
_pyfileconf_logo.set_color("8", "#68bcfa")
_pyfileconf_logo.set_color("9", "#136113")
_pyfileconf_logo.set_color("10", "#ea743a")
_pyfileconf_logo.set_color("11", "#ae7868")
_pyfileconf_logo.set_color("12", "#eaf163")
_pyfileconf_logo.set_color("border", "#000")
pyfileconf_logo = ProjectLogo("pyfileconf", _pyfileconf_logo)

_finstmt_logo = Triangle()
_finstmt_logo.set_color("1", "#bdbb19")
_finstmt_logo.set_color("2", "#8a36dc")
_finstmt_logo.set_color("3", "#676e46")
_finstmt_logo.set_color("4", "#1eb225")
_finstmt_logo.set_color("5", "#b8f9ec")
_finstmt_logo.set_color("6", "#8f3309")
_finstmt_logo.set_color("7", "#035ab4")
_finstmt_logo.set_color("8", "#f8dec5")
_finstmt_logo.set_color("9", "#8d034c")
_finstmt_logo.set_color("10", "#736fc8")
_finstmt_logo.set_color("11", "#8bafd0")
_finstmt_logo.set_color("12", "#496360")
_finstmt_logo.set_color("border", "#000")
finstmt_logo = ProjectLogo("finstmt", _finstmt_logo)

_regtools_logo = Triangle()
_regtools_logo.set_color("1", "#23b5ff")
_regtools_logo.set_color("2", "#563801")
_regtools_logo.set_color("3", "#558280")
_regtools_logo.set_color("4", "#e896e0")
_regtools_logo.set_color("5", "#128361")
_regtools_logo.set_color("6", "#2af14c")
_regtools_logo.set_color("7", "#d47847")
_regtools_logo.set_color("8", "#1abc5d")
_regtools_logo.set_color("9", "#aabedf")
_regtools_logo.set_color("10", "#3038b8")
_regtools_logo.set_color("11", "#5fda14")
_regtools_logo.set_color("12", "#7b375e")
_regtools_logo.set_color("border", "#000")
regtools_logo = ProjectLogo("regtools", _regtools_logo)

_sensitivity_logo = Triangle()
_sensitivity_logo.set_color("1", "#c5dba6")
_sensitivity_logo.set_color("2", "#c75f3b")
_sensitivity_logo.set_color("3", "#2f22c8")
_sensitivity_logo.set_color("4", "#eb1101")
_sensitivity_logo.set_color("5", "#3a43f6")
_sensitivity_logo.set_color("6", "#f35aab")
_sensitivity_logo.set_color("7", "#612eee")
_sensitivity_logo.set_color("8", "#44c6e6")
_sensitivity_logo.set_color("9", "#f7ed47")
_sensitivity_logo.set_color("10", "#479f0c")
_sensitivity_logo.set_color("11", "#660aa6")
_sensitivity_logo.set_color("12", "#d0fd5e")
_sensitivity_logo.set_color("border", "#000")
sensitivity_logo = ProjectLogo("sensitivity", _sensitivity_logo)

_repo_splitter_logo = Triangle()
_repo_splitter_logo.set_color("1", "#f36989")
_repo_splitter_logo.set_color("2", "#a70c23")
_repo_splitter_logo.set_color("3", "#373a65")
_repo_splitter_logo.set_color("4", "#d3a6c2")
_repo_splitter_logo.set_color("5", "#a2cd93")
_repo_splitter_logo.set_color("6", "#a52895")
_repo_splitter_logo.set_color("7", "#c6422b")
_repo_splitter_logo.set_color("8", "#ae2a70")
_repo_splitter_logo.set_color("9", "#37ab91")
_repo_splitter_logo.set_color("10", "#db1c01")
_repo_splitter_logo.set_color("11", "#5a6eac")
_repo_splitter_logo.set_color("12", "#e93790")
_repo_splitter_logo.set_color("border", "#000")
repo_splitter_logo = ProjectLogo("repo_splitter", _repo_splitter_logo)

_projectreport_logo = Triangle()
_projectreport_logo.set_color("1", "#000527")
_projectreport_logo.set_color("2", "#282715")
_projectreport_logo.set_color("3", "#458c03")
_projectreport_logo.set_color("4", "#a745e3")
_projectreport_logo.set_color("5", "#e34cd3")
_projectreport_logo.set_color("6", "#2916e0")
_projectreport_logo.set_color("7", "#227a0a")
_projectreport_logo.set_color("8", "#147a7a")
_projectreport_logo.set_color("9", "#0add56")
_projectreport_logo.set_color("10", "#1cf1d1")
_projectreport_logo.set_color("11", "#cd4937")
_projectreport_logo.set_color("12", "#f10843")
_projectreport_logo.set_color("border", "#000")
projectreport_logo = ProjectLogo("projectreport", _projectreport_logo)

_pd_utils_logo = Triangle()
_pd_utils_logo.set_color("1", "#cd8a03")
_pd_utils_logo.set_color("2", "#8289b4")
_pd_utils_logo.set_color("3", "#e4c482")
_pd_utils_logo.set_color("4", "#3bbb0d")
_pd_utils_logo.set_color("5", "#96bdb5")
_pd_utils_logo.set_color("6", "#40645c")
_pd_utils_logo.set_color("7", "#517af7")
_pd_utils_logo.set_color("8", "#475692")
_pd_utils_logo.set_color("9", "#fe3af2")
_pd_utils_logo.set_color("10", "#d7b1c0")
_pd_utils_logo.set_color("11", "#1b7115")
_pd_utils_logo.set_color("12", "#1dd024")
_pd_utils_logo.set_color("border", "#000")
pd_utils_logo = ProjectLogo("pd_utils", _pd_utils_logo)

_bibtex_gen_logo = Triangle()
_bibtex_gen_logo.set_color("1", "#540d37")
_bibtex_gen_logo.set_color("2", "#6f4c4e")
_bibtex_gen_logo.set_color("3", "#2fdca6")
_bibtex_gen_logo.set_color("4", "#03e65e")
_bibtex_gen_logo.set_color("5", "#5d3b9d")
_bibtex_gen_logo.set_color("6", "#325f09")
_bibtex_gen_logo.set_color("7", "#1ce193")
_bibtex_gen_logo.set_color("8", "#26cb12")
_bibtex_gen_logo.set_color("9", "#9479e6")
_bibtex_gen_logo.set_color("10", "#afee09")
_bibtex_gen_logo.set_color("11", "#75b092")
_bibtex_gen_logo.set_color("12", "#a661bf")
_bibtex_gen_logo.set_color("border", "#000")
bibtex_gen_logo = ProjectLogo("bibtex_gen", _bibtex_gen_logo)

_objcache_logo = Triangle()
_objcache_logo.set_color("1", "#3a8c9a")
_objcache_logo.set_color("2", "#9166ae")
_objcache_logo.set_color("3", "#f05390")
_objcache_logo.set_color("4", "#088848")
_objcache_logo.set_color("5", "#2c18fc")
_objcache_logo.set_color("6", "#130e18")
_objcache_logo.set_color("7", "#b6caaa")
_objcache_logo.set_color("8", "#2958e6")
_objcache_logo.set_color("9", "#98c4d4")
_objcache_logo.set_color("10", "#7d625d")
_objcache_logo.set_color("11", "#595e69")
_objcache_logo.set_color("12", "#05a601")
_objcache_logo.set_color("border", "#000")
objcache_logo = ProjectLogo("objcache", _objcache_logo)

_processfiles_logo = Triangle()
_processfiles_logo.set_color("1", "#f9adea")
_processfiles_logo.set_color("2", "#4433c3")
_processfiles_logo.set_color("3", "#0f1cfc")
_processfiles_logo.set_color("4", "#695c63")
_processfiles_logo.set_color("5", "#a13808")
_processfiles_logo.set_color("6", "#2fceb6")
_processfiles_logo.set_color("7", "#5acffa")
_processfiles_logo.set_color("8", "#1e86e8")
_processfiles_logo.set_color("9", "#4f210e")
_processfiles_logo.set_color("10", "#476b3e")
_processfiles_logo.set_color("11", "#765895")
_processfiles_logo.set_color("12", "#dc433b")
_processfiles_logo.set_color("border", "#000")
processfiles_logo = ProjectLogo("processfiles", _processfiles_logo)

_mixins_logo = Triangle()
_mixins_logo.set_color("1", "#19f82f")
_mixins_logo.set_color("2", "#ade67a")
_mixins_logo.set_color("3", "#a9f949")
_mixins_logo.set_color("4", "#21d11d")
_mixins_logo.set_color("5", "#9d8d9c")
_mixins_logo.set_color("6", "#25529f")
_mixins_logo.set_color("7", "#386025")
_mixins_logo.set_color("8", "#d00504")
_mixins_logo.set_color("9", "#7d243e")
_mixins_logo.set_color("10", "#865946")
_mixins_logo.set_color("11", "#e278b2")
_mixins_logo.set_color("12", "#a131f4")
_mixins_logo.set_color("border", "#000")
mixins_logo = ProjectLogo("mixins", _mixins_logo)

_nick_derobertis_site_logo = ND()
_nick_derobertis_site_logo.set_color("background", "#e44f4f")
_nick_derobertis_site_logo.set_color("foreground", "white")
nick_derobertis_site_logo = ProjectLogo("nick_derobertis_site", _nick_derobertis_site_logo)

LOGOS = [obj for obj in globals().values() if isinstance(obj, ProjectLogo)]
