[tool.poetry]
name = "meliorateapp"
version = "0.1.0"
description = "A code generator and test runner for C++"
authors = ["David Walker <diwalkerdev@twitter.com>"]
license = "MPL 2.0"
readme = "README.md"
homepage = "https://github.com/diwalkerdev/Meliorate"
repository = "https://github.com/diwalkerdev/Meliorate"
keywords = ["cpp", "unit-testing", "poetry", "python", "linux", "windows", "macos"]
include = ["LICENSE"]
classifiers = [
	"Development Status :: 3 - Alpha",
	"Environment :: Console",
	"Intended Audience :: Developers", 
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
	"Operating System :: OS Independent",
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Testing",
]

[tool.poetry.dependencies]
python = "^3.8"
clang = "^6.0.0"
jinja2 = "^2.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
meliorateapp = "meliorateapp.main:script_entry"
