from distutils.core import setup
setup(
  name = 'Videira', 
  packages = ['Videira'],
  version = 'v0.0.0',
  license='MIT',
  description = 'Using OOP access a dict values as attributes.',
  author = 'Zaú Júlio, Anderson Felipe',
  author_email = 'zauhdf@gmail.com, andersonfelipe01@live.com',
  url = 'https://github.com/ZauJulio/Videira',
  download_url = 'https://github.com/ZauJulio/Videira/releases/download/v0.0.0/Videira-v0.0.0.tar.gz',
  keywords = ['class', 'dictToClass', 'dict', 'converting', 'type'],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
  ],
)