
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-03T16:05:20-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f1dd3c9fd981a6e58e8b4786ab928ccebee227ac",
 "version": "1.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
