[tool.poetry]
name = "jrpyanalytics"
version = "0.1.7"
description = "Jumping Rivers: Predictive Analytics in Python"
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.5"
sklearn = "^0.0.0"
numpy = "^1.15"
pandas = "^0.23.4"
matplotlib = "^3.0"
seaborn = "^0.9.0"
graphviz = "^0.10.1"
jrpytests = "^0.1.4"

[tool.poetry.dev-dependencies]
