[tool.poetry]
name = "thingserver"
version = "0.2.1"
description = "HTTP Web Thing implementation"
readme = "README.md"
authors = ["Joel Collins <joel@jtcollins.net>", "Mozilla IoT <iot@mozilla.com>"]
license = "MPL-2.0"
classifiers=[
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
]

[tool.poetry.dependencies]
python = "^3.6"
ifaddr = "^0.1.7"
pyee = "^7.0.2"
jsonschema = "^3.2.0"
tornado = "^6.0.4"
zeroconf = "^0.28.3"

[tool.poetry.dev-dependencies]
pydocstyle = "^5.1.1"
flake8 = "^3.8.3"
black = "^20.8b1"
isort = "^5.5.0"

[tool.black]
exclude = '(\.eggs|\.git|\.venv)'

[tool.isort]
multi_line_output=3
include_trailing_comma=true
force_grid_wrap=0
use_parentheses=true
line_length=88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"