from distutils.core import setup
setup(
    name='mgprint',
    packages=['mgprint'],
    version='0.1',
    license='MIT',
    description='Magic printer for Python CLI',
    author='Fernando Olivera',
    author_email='ferxxel@gmail.com',
    url='https://github.com/fergeek/mgprint',
    download_url='https://github.com/fergeek/mgprint/archive/v0.1.tar.gz',
    python_requires='>=2.7',
    keywords=[
        'mgprint',  'cprint',
        'print',    'magicprint',
        'magic',    '8bits',
        '256bits',  '256color',
        '16bits',   'cli', 'hex',
        'clicolor', 'rgb', 'html',
        'console',  'terminal',
        'easy', 'stable', 'linux',
        'win', 'cmd', 'macos',
        'clicolor', 'cprint',
        'color', 'ascii'],
    classifiers=[
                 'Development Status :: 3 - Alpha',
                 'License :: OSI Approved :: MIT License',
                 'Operating System :: OS Independent',
                 'Intended Audience :: Developers',
                 'Programming Language :: Python',
                 'Programming Language :: Python :: 2.7',
                 'Programming Language :: Python :: 3.3',
                 'Programming Language :: Python :: 3.4',
                 'Programming Language :: Python :: 3.5',
                 'Programming Language :: Python :: 3.6',
                 'Programming Language :: Python :: 3.7',
                 'Programming Language :: Python :: 3.8',
                 'Programming Language :: Python :: 3.9'],
)
