
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-31T09:23:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3fcba338d2cec6c86a336d79553a031d3f31bce2",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
