# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

before_script:
  - apt-get update -q -y
  - export LC_ALL="en_US.UTF-8"
  - export LC_CTYPE="en_US.UTF-8"
  - python --version
  - pip install -e ".[dev]"

stages:
  - Static Analysis
  - Test
  - Coverage
  - Packaging

flake8:
  stage: Static Analysis
  script:
    - make flake8

pylint:
  stage: Static Analysis
  script:
    - make pylint

pycodestyle:
  stage: Static Analysis
  script:
    - make pycodestyle

pydocstyle:
  stage: Static Analysis
  script:
    - make pydocstyle

test:
  stage: Test
  script:
    - make test

coverage:
  stage: Coverage
  coverage: '/TOTAL.+?(\d+)%/'
  script:
    - make coverage
