[tool.poetry]
name = "pddl2gym"
version = "0.0.1"
description = "A translator from PDDL domain/problem files to OpenAI Gym environment."
authors = ["MarcoFavorito <marco.favorito@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
