[tool.poetry]
name = "cy_weather_api"
version = "0.1.0"
description = "Caiyun Weather API Python SDK"
authors = ["ringsaturn <ringsaturn.me@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"
requests = "^2.23.0"
orjson = "^3.0.0"
dacite = "^1.5.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.3.0"
black = "^19.10b0"
flake8 = "isort"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
