[tool.poetry]
name = "breaktimer"
version = "0.1.0"
description = ""
authors = ["Joben R <joben.rara@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
rich = "^6.0.0"
pyfiglet = "^0.8.post1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
