[package]
name = "entab-py"
version = "0.2.0"
authors = ["Roderick <rbovee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
entab_base = { package = "entab", path = "../entab", default-features = false, features = ["std", "compression_manylinux"] }
memmap = "0.7"
pyo3 = "0.11.1"

[lib]
name = "entab"
crate-type = ["cdylib"]

[features]
maturin = ["pyo3/extension-module"]
