
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-06T16:16:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d65c40ccff28d56cb90fed6dfc2645abf5495ac",
 "version": "0.0.06"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
