# This file automatically generated by
#    /home/couchbase/jenkins/workspace/python/sdk/python-scripted-build-pipeline/couchbase-python-client/couchbase_version.py
# at
#    2020-09-04 11:57:09.941683
__version__ = '3.0.5'