[tool.towncrier]
# Read https://github.com/ethereum/lahja/newsfragments/README.md for instructions
package = "lahja"
filename = "docs/release_notes.rst"
directory = "newsfragments"
underlines = ["-", "~", "^"]
issue_format = "`#{issue} <https://github.com/ethereum/lahja/issues/{issue}>`__"