[tool.poetry]
name = "wagtail-cloudinary-image"
version = "0.0.3"
description = "Wagtail Image model that utilized django-cloudinary-storage"
authors = ["David Burke <david@burkesoftware.com>"]
license = "Apache License"
classifiers=[
    "Development Status :: 5 - Production/Stable",
    'Environment :: Web Environment',
    'Framework :: Django',
    'Framework :: Wagtail',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Intended Audience :: Developers',
    "License :: OSI Approved :: Apache Software License",
]

[tool.poetry.dependencies]
python = "^3.7"
wagtail = ">=2.9"
Django = ">=2.2"
cloudinary = ">=1.22.0"
django-cloudinary-storage = ">=0.3.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.2"
black = "^19.10b0"
django-debug-toolbar = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
