name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      NO_ET: 1

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - ubuntu-18.04
          - macos-latest
        python:
          - 3.6  # will also be used to test with _DANDI_LOG_GIRDER set
          - 3.7
          - 3.8

    steps:
    - name: Set up environment
      uses: actions/checkout@v1
      with:
        # Fetch all commits so that versioneer will return something compatible
        # with semantic-version
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"
    - name: Set environment variable when using Python 3.6 to cover more code
      run: echo "::set-env name=DANDI_LOG_GIRDER::1"
      if: matrix.python == '3.6'
    - name: ${{ matrix.module }} tests
      run: |
        python -m pytest -s -v --cov=dandi --cov-report=xml dandi
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        # name: codecov-umbrella
        # yml: ./codecov.yml
        fail_ci_if_error: false
