sudo: false
language: python
cache: pip
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: pypy2.7-5.10.0
    env: TOXENV=pypy
  - python: pypy3.5-5.10.1
    env: TOXENV=pypy3
  - python: 3.6
    env: TOXENV=coverage
install:
  - if [ x$TOXENV == "xcoverage" ]; then pip install coveralls; fi
  - pip install tox
script:
  - tox
after_success:
  - if [ x$TOX_ENV == "xcoverage" ]; then coveralls; fi
