[tool.poetry]
name = "django-component"
version = "0.1.7"
description = "Django template tags to create composable components"
license = "MIT"
authors = ["Jérôme Bon <bon.jerome@protonmail.com>"]
readme = "README.rst"
homepage = "https://gitlab.com/Mojeer/django_components"
repository = "https://gitlab.com/Mojeer/django_components"
keywords = ["django", "components", "template"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]

[tool.poetry.dependencies]
python = ">=3.6"
django = ">=1.11"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
tox = "^3.0"
mypy = "^0.761"
black = "^19.10b0"
pytest-cov = "^2.8.1"
pre-commit = "^1.21.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
