stages:
  - test
  - deploy

centos7:
  except:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:centos7
  script:
    - python --version
    - pip install --upgrade setuptools
    - pip install pycodestyle importlib nose coverage
    - python setup.py install
    - nosetests --with-coverage --cover-package=lbinstall  --cover-html --with-xunit
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

slc6:
  except:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:slc6
  script:
    - python --version
    - pip install --upgrade setuptools
    - pip install pycodestyle importlib nose coverage SQLAlchemy==1.1.14
    - python setup.py install
    - nosetests --with-coverage --cover-package=lbinstall  --cover-html --with-xunit
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

python2.7:
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-2.7
  script:
    - python --version
    - pip install pycodestyle importlib nose coverage
    - python setup.py install
    - nosetests --with-coverage --cover-package=lbinstall  --cover-html --with-xunit
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
    - python setup.py bdist_wheel --dist-dir public/lbinstall
    - python setup.py sdist --dist-dir public/lbinstall
  artifacts:
    paths:
      - cover_report
      - pep8_report
      - public
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

python3.5:
  except:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.5
  script:
    - python --version
    - pip install pycodestyle nose coverage
    - python setup.py install
    - nosetests --with-coverage --cover-package=lbinstall  --cover-html --with-xunit
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
  artifacts:
    paths:
      - cover_report
      - pep8_report
    when: always
    expire_in: 1 week
  tags:
    - cvmfs
 
python3.6:
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.6
  script:
    - python --version
    - pip install pycodestyle nose coverage
    - python setup.py install
    - nosetests --with-coverage --cover-package=lbinstall  --cover-html --with-xunit
    - pycodestyle lbinstall/ > pep8_report.txt || true
    - mkdir -p cover_report && mv -f cover cover_report/$CI_JOB_NAME
    - mkdir -p pep8_report && mv -f pep8_report.txt pep8_report/$CI_JOB_NAME.txt
    - python setup.py bdist_wheel --dist-dir public/lbinstall
  artifacts:
    paths:
      - cover_report
      - pep8_report
      - public
    when: always
    expire_in: 1 week
  tags:
    - cvmfs

# see https://gitlab.cern.ch/gitlabci-examples/deploy_eos for the details
# of the configuration
deploy-packages:
  stage: deploy
  only:
    - tags
  image: gitlab-registry.cern.ch/lhcb-docker/python-deployment:python-3.6
  script:
    - python --version
    - pip install twine
    - twine upload -u $TWINE_USERNAME -p $TWINE_PASSWORD public/lbinstall/*
  tags:
    - cvmfs  
  before_script: []
  after_script: []


