---
sudo: required
services: docker
language: generic
dist: xenial
addons:
  apt:
    packages:
      - libssl1.0.0

before_script:
  - sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.8 python3.8-dev python3.8-distutils
  - sudo pip install tox
  - sudo -E docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - (cd .. && git clone https://github.com/estesp/manifest-tool)
  - (cd ../manifest-tool && git checkout v0.9.0)
  - (cd ../manifest-tool && sudo -E make && sudo -E make install)

jobs:
  include:
    - stage: run unit tests
      script: >
        tox -e docs,pep8,pylint,yamllint,ansiblelint,bashate,py27,py38,cover
    - stage: build xtesting images
      script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - arch="amd64"
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - arch="arm"
    - script: sudo -E bash build.sh
      env:
        - REPO="${DOCKER_USERNAME}"
        - arch="arm64"
    - stage: publish xtesting manifests
      script: >
        sudo manifest-tool push from-args \
          --platforms linux/amd64,linux/arm,linux/arm64 \
          --template ${DOCKER_USERNAME}/xtesting:ARCH-kali \
          --target ${DOCKER_USERNAME}/xtesting:kali
