[tool.poetry]
name = "perimod"
version = "1.0.1"
description = "Peridot module maker in Python"
authors = ["Totobird"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
