[tool.poetry]
name = "jrpyml"
version = "0.2.8"
description = "Jumping Rivers: Machine Learning in Python"
authors = ["Jamie <jamie@jumpingrivers.com>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.16"
pandas = "^0.23.4"
matplotlib = "^3.1"
statsmodels = "^0.9.0"
scipy = "=1.2"
sklearn = "^0.0.0"
jrpyanalytics = ""

[tool.poetry.dev-dependencies]
