"""
Author: qiacai
"""

"""
Constants to use for ada
"""

"""
Constants for algorithms
"""
ALGORITHM_DEFAULT_WINDOW_REGEX = '^(-|)([0-9]*)(y|M|w|d|h|m|s|[0-9])$'

ALGORITHM_DEFAULT_TIMEZONE = 'US/Pacific'

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_TIMESTAMP_LEFT_IN = True

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_TIMESTAMP_RIGHT_IN = True

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_TIMESTAMP_DIRECT = False

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_WINDOW_LEFT_IN = False

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_WINDOW_RIGHT_IN = True

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_WINDOW_DIRECT = False

ALGORITHM_DEFAULT_BI_OPERATION_ENCLOSE = False

ALGORITHM_DEFAULT_CALCULATOR_PERCENTILE_PERCENTILE = 50

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_PERCENTILE = 5

ALGORITHM_DEFAULT_CALCULATOR_SIMPLE_MA_SMOOTHING_WINDOW = '3'

ALGORITHM_DEFAULT_CALCULATOR_SPLIT_WINDOW_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_CALCULATOR_SIMPLE_MA_SMOOTHING_DIRECTION = 'backward'

ALGORITHM_DEFAULT_CALCULATOR_SIMPLE_MA_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_CALCULATOR_EXPONENTIAL_MA_SMOOTHING_FACTOR = 0.3

ALGORITHM_DEFAULT_CALCULATOR_EXPONENTIAL_MA_SMOOTHING_DIRECTION = 'both'

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_PERIOD_WINDOW = '24'

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_TREND_ONLY = False

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_FILLNA = False

ALGORITHM_DEFAULT_CALCULATOR_SEASONAL_DECOMPOSE_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_CALCULATOR_FILTER_WITH_PERIOD_PERIOD_WINDOW = '1'

ALGORITHM_DEFAULT_CALCULATOR_FILTER_WITH_PERIOD_ALIGN_POINT = 'end'

ALGORITHM_DEFAULT_CALCULATOR_FILTER_WITH_PERIOD_DIRECT = False

ALGORITHM_DEFAULT_CALCULATOR_FILTER_WITH_PERIOD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_UPPER_PERCENTILE = 95

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_LOWER_PERCENTILE = 5

ALGORITHM_DEFAULT_CALCULATOR_CUSHION_IS_UPPER = True

ALGORITHM_DEFAULT_CALCULATOR_VALUE_ARITHMETIC_FILL_VALUE = False

ALGORITHM_DEFAULT_CALCULATOR_VALUE_COMPARISON_FILL_VALUE = False

ALGORITHM_DEFAULT_CALCULATOR_ROUND_NDIGITS = 0

ALGORITHM_DEFAULT_CALCULATOR_TIME_OFFSET_OFFSET_WINDOW = 0

ALGORITHM_DEFAULT_HARD_THRESHOLD_THRESHOLD = 0

ALGORITHM_DEFAULT_HARD_THRESHOLD_OPERATOR = '>'

ALGORITHM_DEFAULT_HARD_THRESHOLD_LOCAL_WINDOW = '1'

ALGORITHM_DEFAULT_HARD_THRESHOLD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE


ALGORITHM_DEFAULT_SOFT_THRESHOLD_OPERATOR = '>'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_LOCAL_WINDOW = '1'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_BENCHMARK_SIZE = '1'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_BENCHMARK_METHOD = 'mean'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_BOUND_METHOD = 'std'

ALGORITHM_DEFAULT_SOFT_THRESHOLD_FACTOR = 3

ALGORITHM_DEFAULT_SOFT_THRESHOLD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_SOFT_THRESHOLD_PERIOD_WINDOW = 0

ALGORITHM_DEFAULT_SOFT_THRESHOLD_PERIOD_METHOD = 'filter_by_period'

ALGORITHM_DEFAULT_BI_SOFT_THRESHOLD_ENCLOSE = ALGORITHM_DEFAULT_BI_OPERATION_ENCLOSE


ALGORITHM_DEFAULT_CUSHION_THRESHOLD_OPERATOR = '>'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_LOCAL_WINDOW = '1'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_BENCHMARK_SIZE = '1'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_BENCHMARK_METHOD = 'mean'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_BOUND_METHOD = 'std'

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_FACTOR = 2

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_TIMEZONE = ALGORITHM_DEFAULT_TIMEZONE

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_UPPER_PERCENTILE = ALGORITHM_DEFAULT_CALCULATOR_CUSHION_UPPER_PERCENTILE

ALGORITHM_DEFAULT_CUSHION_THRESHOLD_LOWER_PERCENTILE = ALGORITHM_DEFAULT_CALCULATOR_CUSHION_LOWER_PERCENTILE

ALGORITHM_DEFAULT_BI_CUSHION_THRESHOLD_ENCLOSE = ALGORITHM_DEFAULT_BI_OPERATION_ENCLOSE




