[tool.black]
line-length = 100
target-version = ["py36", "py37"]
skip-numeric-underscore-normalization = true
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|build|dist|migrations)/'

[tool.towncrier]
package = "pulp_cookbook"
filename = "CHANGES.rst"
directory = "CHANGES/"
title_format = "{version} ({project_date})"
template = "CHANGES/.TEMPLATE.rst"
issue_format = "`#{issue} <https://github.com/gmbnomis/pulp_cookbook/issues/{issue}>`_"
