[tool.poetry]
name = "nersi"
version = "0.1.1"
description = "A package for easily calculating the Network-Extended Residual Supply Index (NERSI), a measure of market concentration and pivotality for nodal electricity networks."
authors = ["Luke Marshall <lukasmarshall@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
networkx = "^2.5"
matplotlib = "^3.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
