[tool.poetry]
name = "aio_zmq_rpc"
version = "0.1.0"
description = ""
authors = ["Alexander Titoff <a.tit.off@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
zmq = "^0.0.0"
msgpack = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
