[tool.poetry]
name = "jdv-nulltype"
version = "1.0.1"
description = "A singleton Null object in Python."
authors = ["Justin Vrana <justin.vrana@gmail.com>"]
packages = [
    {include = "nulltype"}
]

[tool.poetry.dependencies]
python = "^3.5"
keats = "^0.2.28"

[tool.poetry.dev-dependencies]
pytest = [
    {version = "^5.0.0", python="^3.5"}
]
keats = "^0.2.28"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"