[tool.poetry]
name = "pyflowcl"
version = "1.0.1"
description = "Cliente para comunicacion con flowAPI-3 de flow.cl"
authors = ["Mario Hernandez <yo@mariofix.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/mariofix/pyflowcl"
classifiers=[
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-pep8 = "^1.0.6"
black = "^19.10b0"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
