from typing import Dict, NoReturn, Type, TypeVar

_T = TypeVar("_T")

class Settings:
    settings: Dict
    configured: bool
    def __init__(self): ...
    def __getattr__(self, name: str): ...
    def configure(self) -> NoReturn: ...
    def reset(self) -> NoReturn: ...
    def load(self, klass: Type[_T]) -> _T: ...

settings: Settings
