[tool.poetry]
name = "savvihub-client"
version = "0.0.4"
description = "A Command line interface and library for SavviHub"
authors = ["Floyd Ryoo <floyd@savvihub.com>"]
readme = "savvihub_cli/README.md"

[tool.poetry.scripts]
savvi = "savvihub_cli.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
