
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a2588694c3d7cb2f16c1f3212a37e7207cd598a6",
 "version": "1.3.0.7.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
