[tool.poetry]
name = "ds3"
version = "0.1.0"
description = "The S3 API for Python"
authors = ["Tomas Pereira de Vasconcelos <tomasvasconcelos1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
