[tool.poetry]
name = "ledregulator"
version = "0.11.0"
description = ""
authors = ["DonQueso89 <kg.v.ekeren@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.61.1"
uvicorn = "^0.11.8"

[tool.poetry.scripts]
runserver = 'ledregulator.runserver:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
