
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-04T10:32:46-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "74f14106810d85ce70e46e510b1f7a306c894dcd",
 "version": "0.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
