[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "nornir"
version = "2.5.0"
description = "Pluggable multi-threaded framework with inventory management to help operate collections of devices"
authors = ["David Barroso <dbarrosop@dravetech.com>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/nornir-automation/nornir"
classifiers = [
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
]

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.1"
jinja2 = "^2"
napalm = ">=2.5.0"
netmiko = ">=2.4.2"
paramiko = "^2.7"
requests = "^2"
"ruamel.yaml" = "^0.16"
mypy_extensions = "^0.4.1"
# The following dependencies are used for docs generation when installed as extras
# (e.g. pip install nornir[docs])
# Currently they have to be specified as non-dev dependencies with optional = true
# Refer to: https://github.com/sdispater/poetry/issues/129
sphinx = { version = "^1", optional = true }
sphinx_rtd_theme = { version = "^0.4", optional = true }
sphinxcontrib-napoleon = { version = "^0.7", optional = true }
jupyter = { version = "^1", optional = true }
nbsphinx = { version = "^0.5", optional = true }
pygments = { version = "^2", optional = true }
sphinx-issues = { version = "^1.2", optional = true }
typing_extensions = "^3.7"
ncclient = "^0.6.6"

# for pydantic
dataclasses = {version = "^0.7", python = "~3.6"}

[tool.poetry.dev-dependencies]
decorator = "*"
nbval = "*"
pytest = "*"
pytest-cov = "*"
pylama = "*"
requests-mock = "*"
black = { version = "19.10b0", allow-prereleases = true }
mypy = "*"
# The following dependencies are used for docs generation when run locally or in Docker
# (e.g. poetry install)
sphinx = "^1"
sphinx_rtd_theme = "^0.4"
sphinxcontrib_napoleon = "^0.7"
jupyter = "^1"
nbsphinx = "^0.5"
pygments = "^2"
sphinx-issues = "^1.2"

[tool.poetry.extras]
# The following section is required to install docs dependencies
# until RTD fully supports poetry: https://github.com/rtfd/readthedocs.org/issues/4912
docs = ["sphinx", "sphinx_rtd_theme", "sphinxcontrib-napoleon", "jupyter", "nbsphinx", "pygments", "sphinx-issues"]
