from . import subscription_request
from . import coop_agreement
from . import res_partner
from . import contract
from . import service_technology
from . import service_supplier
from . import product_category_technology_supplier
from . import ir_model_data
from . import crm_lead
from . import crm_lead_line
from . import previous_provider
from . import isp_info
