# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from mms_python_client.configuration import Configuration


class PermissionsRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'users': 'PermissionUpdateRequest',
        'groups': 'PermissionUpdateRequest',
        'inherit': 'bool',
        'public': 'bool'
    }

    attribute_map = {
        'users': 'users',
        'groups': 'groups',
        'inherit': 'inherit',
        'public': 'public'
    }

    def __init__(self, users=None, groups=None, inherit=None, public=None, local_vars_configuration=None):  # noqa: E501
        """PermissionsRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._users = None
        self._groups = None
        self._inherit = None
        self._public = None
        self.discriminator = None

        if users is not None:
            self.users = users
        if groups is not None:
            self.groups = groups
        if inherit is not None:
            self.inherit = inherit
        if public is not None:
            self.public = public

    @property
    def users(self):
        """Gets the users of this PermissionsRequest.  # noqa: E501


        :return: The users of this PermissionsRequest.  # noqa: E501
        :rtype: PermissionUpdateRequest
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this PermissionsRequest.


        :param users: The users of this PermissionsRequest.  # noqa: E501
        :type: PermissionUpdateRequest
        """

        self._users = users

    @property
    def groups(self):
        """Gets the groups of this PermissionsRequest.  # noqa: E501


        :return: The groups of this PermissionsRequest.  # noqa: E501
        :rtype: PermissionUpdateRequest
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this PermissionsRequest.


        :param groups: The groups of this PermissionsRequest.  # noqa: E501
        :type: PermissionUpdateRequest
        """

        self._groups = groups

    @property
    def inherit(self):
        """Gets the inherit of this PermissionsRequest.  # noqa: E501


        :return: The inherit of this PermissionsRequest.  # noqa: E501
        :rtype: bool
        """
        return self._inherit

    @inherit.setter
    def inherit(self, inherit):
        """Sets the inherit of this PermissionsRequest.


        :param inherit: The inherit of this PermissionsRequest.  # noqa: E501
        :type: bool
        """

        self._inherit = inherit

    @property
    def public(self):
        """Gets the public of this PermissionsRequest.  # noqa: E501


        :return: The public of this PermissionsRequest.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this PermissionsRequest.


        :param public: The public of this PermissionsRequest.  # noqa: E501
        :type: bool
        """

        self._public = public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PermissionsRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PermissionsRequest):
            return True

        return self.to_dict() != other.to_dict()
