[tool.poetry]
name = "cdm-orm"
version = "0.1.1"
description = ""
authors = ["mountain <tim@lustberg.nl>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
