[tool.poetry]
name = "mrsr"
version = "0.1.0"
description = ""
authors = ["Madson Dias <madsonddias@gmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/omadson/mrsr"
repository = "https://github.com/omadson/mrsr"
keywords = ["machine-learning", "data-science", "mrsr", "sparse-regression"]
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.15.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
jupyterlab = "^2.2.6"
ipykernel = "^5.3.4"
mnist = "^0.2.2"
scikit-learn = "^0.23.2"
matplotlib = "^3.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
