dist: xenial

language: python

cache:
  pip: true
  timeout: 1000

sudo: false

python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'

os:
- linux

matrix:
  fast_finish: true
  allow_failures:
    - python: '2.7'
    - python: '3.5'

notifications:
  email: false

# repo branches to test
#branches:
#- master

install:
- pip install -U pip wheel --quiet
- pip install --upgrade setuptools --quiet
- pip install .[dev]

script:
- pytest tests --cov tree --cov-report html

after_success:
- coveralls
- codecov
