
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-31T22:22:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0aaac4bd89f7a622a94a5710e2d28b0c62a0cfeb",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
