[tool.poetry]
name = "innvariant"
version = "0.1.0"
description = ""
authors = ["Julian Stier <julian.stier@uni-passau.de>"]

[tool.poetry.dependencies]
python = "^3.6.1"
networkx = { version = "^2.5", optional = true }

[tool.poetry.dev-dependencies]
matplotlib = { version = "^3.3" }
pytest = "^3.0"
black = { version = "^19.10b0", python = "^3.6" }
pre-commit = "^2.3.0"

[tool.poetry.extras]
all = ["networkx"]
networkx = ["networkx"]

[tool.isort]
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py", "res/"]
filter_files = true
known_first_party = "innvariant"
known_third_party = ["numpy", "pytest", "matplotlib"]

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | res
  | build
  | dist
  | tests/.*/setup.py
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
