
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-03T22:52:37-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d19ce52a0a52cec469b559e580b25db4229f2866",
 "version": "v0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
