[tool.poetry]
name = "eventz-aws"
version = "0.4.2"
description = "AWS additions for Eventz framework."
authors = ["Dan Ballance <work@danballance.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
immutables = "^0.14"
boto3 = "^1.14.16"
eventz = "^0.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cover = "^3.0.0"
moto = "^1.3.14"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
