name: Run tests on any merge event

# Запуск при любом merge евенте в любую ветке.

on:
  pull_request:
    branches:
      - '*'

jobs:
  on_merge_check_3_8_ubuntu:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --cov=YamlBase ./test/
          bash <(curl -s https://codecov.io/bash) -t  ${{ secrets.CODECOV_TOKEN }}

  on_merge_check_3_7_ubuntu:
    runs-on: [ubuntu-latest]
    needs: [on_merge_check_3_8_ubuntu]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v ./test

  on_merge_check_3_7_windows:
    needs: [on_merge_check_3_7_ubuntu]
    runs-on: [windows-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v ./test

  on_merge_check_3_8_windows:
    needs: [on_merge_check_3_7_windows]
    runs-on: [windows-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v ./test

  on_merge_check_3_7_macos:
    needs: [on_merge_check_3_8_windows]
    runs-on: [macos-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v ./test
