name: Run tests on any Push event

# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.

on:
  push:
    branches:
      - '*'

jobs:
  on_push_check_3_8:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --cov=YamlBase ./test/
          bash <(curl -s https://codecov.io/bash) -t  ${{ secrets.CODECOV_TOKEN }}

  on_push_check_3_7:
    runs-on: [ubuntu-latest]
    needs: [on_push_check_3_8]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v1
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest --cov=YamlBase ./test/
          bash <(curl -s https://codecov.io/bash) -t  ${{ secrets.CODECOV_TOKEN }}