[tool.poetry]
name = "minionize"
version = "0.1.3"
description = "Massively Parallel operation made easy"
authors = ["msimonin <matthieu.simonin@inria.fr>"]
license = "GPLv3"

readme = "README.rst"

repository = "https://gitlab.inria.fr/msimonin/minionize"

keywords = ["packaging", "dependency", "poetry"]

[tool.poetry.dependencies]
python = "^3.7"
execo = "^2.6.4"
google-cloud-pubsub = "^1.7.0"
python-dotenv = "^0.14.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
mypy = "^0.782"
ipdb = "^0.13.3"

[tool.poetry.scripts]
minionize = 'minionize.cli:run'

[tool.black]
line-length = 88
target_version = ['py37']
include = '\.pyi?$'


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
