
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-03T10:01:01-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b002ca6e377b45308d43d9d96dc5f868f7123cbf",
 "version": "1.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
