[tool.poetry]
name = "interstate-py"
version = "0.7.0"
description = ""
authors = ["LeftshiftOne Software GmbH <devs@leftshift.one>"]

[tool.poetry.dependencies]
python = "^3.5"
pyzmq = "^18.0"
aiozmq = "^0.7.1"
async_generator = "^1.10"
rx = "1.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
pytest-cov = "^2.8.1"
pytest-asyncio = "^0.12.0"
toml = "^0.10.0"

[tool.poetry.scripts]
install = "poetry_scripts:install"
test = "poetry_scripts:test"
build = "poetry_scripts:build"
publish = "poetry_scripts:publish"
release = "poetry_scripts:release" # e.g. poetry run release minor

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
