name: shut
version: "0.1.0"
license: MIT
url: https://git.niklasrosenstein.com/NiklasRosenstein/shore
description: Automates the heavy lifting of release and distribution management for pure Python packages.
author: Niklas Rosenstein <rosensteinniklas@gmail.com>
typed: true

requirements:
  - python ^3.6
  - beautifulsoup4 ^4.8.1
  - databind.core ^0.1.0
  - databind.json ^0.1.0
  - click ^7.0
  - jinja2 ^2.11.1
  - networkx ^2.4
  - nr.fs ^1.5.0
  - nr.pylang.utils ^0.0.1
  - nr.proxy ^0.0.1
  - nr.utils.git ~0.1.3
  - nr.stream
  - requests ^2.22.0
  - packaging ^20.1
  - PyYAML ^5.1.0
  - termcolor ^1.1.0
  - twine
  - wheel

entrypoints:
  console_scripts:
    - shore = shore.__main__:_entry_point
    - shore-conda-forge = shore.tools.conda_forge:main
    - shut = shut.commands:shut
  shore.core.plugins:
    - core = shore.plugins.core:CorePlugin
    - install-script = shore.plugins.install_script:InstallScriptRenderer
    - pypi = shore.plugins.pypi:PypiPublisher
    - requirements-file = shore.plugins.requirements_file:RequirementsFileRenderer
    - setuptools = shore.plugins.setuptools:SetuptoolsRenderer

manifest:
  - include src/shore/templates/install_script/install
  - recursive-include src/shore/templates *.yaml *.py *.md .gitignore
