language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"  # 3.4 & 2.7 only test flit_core - see tox.ini

jobs:
  include:
    - python: "3.8"
      env: TOXENV=bootstrap

install:
  - pip install tox-travis codecov
script: tox
after_success: codecov
