[tool.poetry]
name = "eng_econ"
version = "0.1.2"
description = "This package provides some of the basic functions of engineering economics"
authors = ["Songyu-Wang <wangsongyuf@gmail.com>"]

license = "MIT"
readme = "README.md"
homepage = "https://songyu-wang.github.io/engineering-economics-basics/"
repository = "https://github.com/Songyu-Wang/engineering-economics-basics"
keywords = ["engineering", "economics", "economy"]
classifiers = [
    "Operating System :: OS Independent",
]
include = [
    "LICENSE",
]


[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
autopep8 = "^1.5.4"
black = "^20.8b1"
isort = "^5.4.2"
coverage = "^5.2.1"
pdoc3 = "^0.9.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
