[tool.poetry]
name = "filtrark"
version = "0.9.3"
description = "Build filter clauses from instruction lists"
authors = ["Knowark"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
sphinx = "^3.1.2"
sphinx-autobuild = "^0.7.1"
bump2version = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
