
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2020-09-03T09:05:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b01f01954e4e469c54ca656aa109c82532e1b3d9",
 "version": "0.92.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
