DS_CONFIG_FILE_NAME = 'configuration.json'
DS_PATH_ENV_VAR_NAME = 'DS_PATH'
EXTRACTED_MODEL_DIRECTORY_NAME = 'studiomodelpackage'
GRAPH_SPEC_FILE_NAME = 'modelpackage.json'
MODEL_PARENT_PATH_ENV_VAR_NAME = 'MODEL_PARENT_PATH'
STANDARD_CUSTOM_MODULE_ON_INIT_METHOD_NAME = 'on_init'

COLUMN_ATTRIBUTES_KEY = 'columnAttributes'
