[tool.poetry]
name = "migrark"
version = "0.6.0"
description = "Migration Management Library"
authors = ["Esteban Echeverry <eecheverry@nubark.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
mypy = "^0.720.0"
pytest = "^5.1"
bump2version = "^0.6.01"
pytest-cov = "^2.10.0"
pylint = "^2.5.3"
autopep8 = "^1.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
