
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-31T05:00:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0db92af2312a281d72e9faddfd584d49dc9fb447",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
