[tool.poetry]
name = "tbreader"
version = "1.0.1"
description = "A simple parser for tensorboard files"
authors = ["Daniel Suess <daniel@dsuess.me>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.6"
protobuf = ">=3.8.0"

[tool.poetry.dev-dependencies]
tensorboardx = "^2.1"
black = "19.10b0"
pytest = "^5.0"
pylint = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
