
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-30T14:22:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e65316a5386f8c6f48e181b8b545ec4da95d1fe4",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
