
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-02T13:35:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a19931d6db18d02f9ed6da4b4105f3b60f07966b",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
