
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-04T11:47:20-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fb5ab9c2caa023b91722e1dfc1aac00b6e0d7ec4",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
