
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-16T13:22:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e24aa5b99b1986f946cf64f2f255b1f86d52112",
 "version": "2.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
