# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knpay_plugin', '0003_auto_20170403_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_url',
            field=models.URLField(blank=True, verbose_name='Payment URL'),
        ),
    ]
