# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knpay_plugin', '0004_paymenttransaction_payment_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'get_latest_by': 'created', 'ordering': ('created',), 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
    ]
