[tool.poetry]
name = "faust_avro"
version = "0.4.1"
description = "Avro codec and schema registry support for Faust"
authors = ["Mastery Systems LLC <oss@mastery.net>"]
readme = "README.md"
repository = "https://github.com/masterysystems/faust-avro"
license = "BSD-3-Clause"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Typing :: Typed"
]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
fastavro = "^0.22.5"
faust = "^1.10"
funcy = "^1.13"
typing-inspect = "^0.5.0"

[tool.poetry.dev-dependencies]
assertpy = {version = "^0.15", allows-prereleases = true}
black = {version = "^19.3-beta.0", allows-prereleases = true}
isort = {version = "^4.3", extras = ["pyproject"]}
pre-commit = "^1.18"
pytest = "^3.0"
pytest-asyncio = "^0.10.0"
pytest-cov = "^2.7"
pytest-factoryboy = "^2.0"
pytest-flake8 = "^1.0"
pytest-mypy = "^0.4.0"
pytest-parallel = "^0.0.9"
pytest-vcr = "^1.0"
seed-isort-config = "^1.9"
sphinx = "^2.2"
strawberry-graphql = "^0.20.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = ["aiohttp", "click", "fastavro", "faust", "funcy", "strawberry", "typing_inspect"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
