[tool.poetry]
name = "aioeafm"
version = "1.0.0"
description = "An asyncio wrapper for the UK Environment Agency Flood Monitoring API"
authors = ["John Carr <john.carr@unrouted.co.uk>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.6.1"
aiohttp = "^3.6.1"

[tool.poetry.dev-dependencies]
isort = "^5.5.1"
black = "^20.8b1"
flake8 = "^3.8.3"
pytest-cov = "^2.10.1"
pyupgrade = "^2.7.2"
codecov = "^2.1.9"
mypy = "^0.761"
pytest-aiohttp = "^0.3.0"
pylint = "^2.4.4"

[tool.black]
target-version = ["py36", "py37", "py38"]

[tool.coverage.run]
omit = ["tests/*"]

[tool.isort]
profile = "black"
indent = "    "
force_sort_within_sections = "true"
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
known_first_party = "pytest_docker_tools,tests"
forced_separate = "tests"
combine_as_imports = "true"
extra_standard_library = "_socket"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
