# coding: utf-8

"""
    Honeywell

    This is an api to connect to the Honeywell backend  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: nick@aliroquantum.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import honeywell
from honeywell.models.inline_response_default1 import InlineResponseDefault1  # noqa: E501
from honeywell.rest import ApiException

class TestInlineResponseDefault1(unittest.TestCase):
    """InlineResponseDefault1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponseDefault1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = honeywell.models.inline_response_default1.InlineResponseDefault1()  # noqa: E501
        if include_optional :
            return InlineResponseDefault1(
                error_response = honeywell.models.error_response.ErrorResponse(
                    error = honeywell.models.error_response_error.ErrorResponse_error(
                        code = '0', 
                        text = '0', ), ), 
                job_response = honeywell.models.job_response.JobResponse(
                    job = '0', 
                    status = '0', ), 
                cost = 56, 
                name = '0', 
                submit_date = '0'
            )
        else :
            return InlineResponseDefault1(
                submit_date = '0',
        )

    def testInlineResponseDefault1(self):
        """Test InlineResponseDefault1"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
