from .specgfx import (INIT, 
BORDER, 
INK, PAPER, FLASH, BRIGHT, INVERSE, OVER,
AT, TAB,
PRINT, SET, CLS,
INPUT, INKEYS,
PLOT, DRAW,
UPDATE, AUTOUPDATE, MANUALUPDATE, BYE,
UDG, GETCHARDEF, RESETCHARS)