[tool.poetry]
name = "nbpretty"
version = "0.1.0"
description = ""
authors = ["Matt Williams <matt@milliams.com>"]
license = "MIT"

[tool.poetry.scripts]
nbpretty = "nbpretty:main"

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.1"
nbconvert = "^5.6"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
beautifulsoup4 = "^4.8.2"
mypy = "^0.761"
sphinx = "^3.1.2"
sphinx-autobuild = "^0.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
