[tool.poetry]
name = "peridot_periscope"
version = "1.0.0"
description = "Unit testing framework for the Peri.dot Programming Language"
authors = ["Totobird"]
license = "BSD-3-Clause"
readme = 'README.md'

[tool.poetry.scripts]
periscope = 'peridot_periscope:main'

[tool.poetry.dependencies]
python = "^3.8"
peridot = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
