[tool.poetry]
name = "consoler"
version = "0.1.3"
description = ""
authors = ["Hactar <systems@hactar.is>"]

license = "MIT"
readme = "README.md"
homepage = "https://github.com/hactar-is/consoler"
repository = "https://github.com/hactar-is/consoler"
keywords = ["console", "terminal", "logging"]
classifiers = [
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6"

arrow = "^0.15.5"
loguru = ">=0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
