environment:
  pypi_token:
    secure: /FwQrmudDyj+Mu3DaxLEo23Y6/OEgdHJqyWyZTjkJKje8pxCOrUorN8ZlXRGXbd3UA60emClt0M+SI+xqyA/qkpqZTgd5CKohpVAGH2EfzRc/zwJSGJ4tmZmMVAG8ayk6N9zFxCeC+y0BgZPQnj/Eq/RfuS4YIuaKutIUa5gTMmhWpODFKGV/2Wx1w67xWxAoONfEC5j0Gu3R274SS7FfBb4qWyIiBIJMwHGjlgp1Onk8KlpCLauZv8/hGfQDmWEdZ+mjcsTYyQYr1xfr1/FjQ==
  matrix:
  - TARGET: unittests
    MACHINE_TYPE: "x86"
    PYTHON: "C:\\Python38"
    PYTHON_VERSION: "3.8"
    L2TBINARIES_TRACK: "dev"
  - TARGET: unittests
    MACHINE_TYPE: "amd64"
    PYTHON: "C:\\Python38-x64"
    PYTHON_VERSION: "3.8"
    L2TBINARIES_TRACK: "dev"

install:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86 /release'
- cmd: "%PYTHON%\\python.exe -m pip install -U pip setuptools wheel"
- cmd: "%PYTHON%\\python.exe -m pip install pywin32 WMI"
- cmd: "%PYTHON%\\python.exe %PYTHON%\\Scripts\\pywin32_postinstall.py -install"
- cmd: git clone https://github.com/log2timeline/l2tdevtools.git ..\l2tdevtools
- cmd: IF [%PYTHON_VERSION%]==[3.8] (
    mkdir dependencies &&
    set PYTHONPATH=..\l2tdevtools &&
    "%PYTHON%\\python.exe" ..\l2tdevtools\tools\update.py --download-directory dependencies --machine-type %MACHINE_TYPE% --msi-targetdir "%PYTHON%" --track "%L2TBINARIES_TRACK%" mock pbr six )

build_script:
- cmd: IF [%TARGET%]==[unittests] (
    "%PYTHON%\\python.exe" setup.py bdist_msi bdist_wheel )

test_script:
- cmd: IF [%TARGET%]==[unittests] (
    "%PYTHON%\\python.exe" run_tests.py &&
    IF EXIST "tests\\end-to-end.py" (
        set PYTHONPATH=. &&
        "%PYTHON%\\python.exe" "tests\\end-to-end.py" --debug -c "config\\end-to-end.ini" ) )

artifacts:
- path: dist\*.whl

deploy_script:
- ps: If ($env:APPVEYOR_REPO_TAG -eq "true") {
    Invoke-Expression "${env:PYTHON}\\python.exe -m twine upload dist/*.whl --username __token__ --password ${env:PYPI_TOKEN} --skip-existing" }

