[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "cms_perf"
author = "Max Fischer"
author-email = "maxfischer2781@gmail.com"
home-page = "https://github.com/maxfischer2781/cms_perf"
description-file = "README.rst"
keywords = "xrootd cms.perf"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
]
requires = ["psutil >=5.6.2", "pyparsing", "typing-extensions"]

[tool.flit.scripts]
cms_perf = "cms_perf.report:main"

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=4.3.0",
    "codecov",
    "flake8",
    "flake8-bugbear",
    "black",
    "setproctitle",
]
doc = ["sphinx", "sphinx-tabs"]

[tool.black]
target-version = ['py36', 'py37', 'py38']
