request body:
{
	"conn_type": "",
	"opposite_name": [ErrorDetail(string = "opposite_name为必填字段", code = "required")],
	"line_num": [ErrorDetail(string = "line_num为必填字段", code = "required")],
	"isp_line_num": [ErrorDetail(string = "line_num为必填字段", code = "required")],
	"asn": [ErrorDetail(string = "asn为必填字段", code = "required")],
	"route_ingredient": [ErrorDetail(string = "route_ingredient为必填字段", code = "required")],
	"contract_id": [ErrorDetail(string = "contract_id为必填字段", code = "required")],
	"logic_ap_id": [ErrorDetail(string = "logic_ap为必填字段", code = "required")],
	"phyical_ap_id": [ErrorDetail(string = "phyical_ap为必填字段", code = "required")],
	"logic_ap_phyical_port": [ErrorDetail(string = "logic_ap_phyical_port为必填字段", code = "required")],
	"phyical_ap_phyical_port": [ErrorDetail(string = "phyical_ap_phyical_port为必填字段", code = "required")],
	"logic_ap_port_rate": [ErrorDetail(string = "logic_ap_port_rate为必填字段", code = "required")],
	"phyical_ap_port_rate": [ErrorDetail(string = "phyical_ap_port_rate为必填字段", code = "required")],
	"local_addr": [ErrorDetail(string = "This field is required.", code = "required")],
	"remote_addr": [ErrorDetail(string = "This field is required.", code = "required")],
	"blackholes_type": [ErrorDetail(string = "blackholes_type为必填字段", code = "required")],
	"blackholes_community": [ErrorDetail(string = "blackholes_community为必填字段", code = "required")],
	"committed_bw": [ErrorDetail(string = "committed_bw为必填字段", code = "required")],
	"burst_bw": [ErrorDetail(string = "burst_bw为必填字段", code = "required")],
	"routes_num_type": [ErrorDetail(string = "routes_num_type为必填字段", code = "required")],
	"prefixes_num": [ErrorDetail(string = "routes_num_type为必填字段", code = "required")],
	"blackholes_num": [ErrorDetail(string = "blackholes_num为必填字段", code = "required")],
	"purchase_channel": [ErrorDetail(string = "purchase_channel为必填字段", code = "required")],
	"contract_remind": [ErrorDetail(string = "This field is required.", code = "required")],
	"monetary_unit": [ErrorDetail(string = "monetary_unit为必填字段", code = "required")],
	"burst_billing": [ErrorDetail(string = "burst_billing为必填字段", code = "required")],
	"logic_ap": [ErrorDetail(string = "This field is required.", code = "required")],
	"phyical_ap": [ErrorDetail(string = "This field is required.", code = "required")]
}