
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-01T14:34:43-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f85338dcbcc93806ef6a8d7e43c690205c72e331",
 "version": "0.0.2a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
