language: python
sudo: true
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
#  - 3.9-dev
#  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.9-dev
  - python: nightly
  - python: 3.8
    arch: arm64
  - python: 3.8
    arch: s390x
  include:
  - python: 3.5
    env: ONLY_BUILTINS=1
    install:
      - pip install .
      - pip install .[test]
  - python: 3.8
    env: PARAMSURVEY_VERBOSE=3 PYTEST_STDERR_VISIBLE=-s
#  - python: 3.8
#    arch: arm64  # works but takes 35 minutes
#    env: ONLY_BUILTINS=1
#    install:
#      - pip install .
#      - pip install .[test]
#      # no ray on arm64
#  - python: 3.8
#    arch: s390x  # works but takes 9.25 minutes, needs a hack in unit/test_params/test_param_stress
#    env: ONLY_BUILTINS=1
#    install:
#      - pip install .
#      - pip install .[test]
#      # no ray on s390

git:
  depth: 99999

before_install:
  # temporary workaround for s390x and arm64 permissions problem
  # https://travis-ci.community/t/permission-issue-while-building-wheels-for-various-python-packages/7822/12
  - sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels

install:
  - pip install .
  - pip install .[test]
  - pip install .[ray]
#  - pip install .[mpi]

script:
  - make test_coverage

after_success:
  coveralls
