[tool.poetry]
name = "kivysome"
version = "0.2.1"
description = "Font Awesome 5 Icons for Kivy"
authors = ["matfax <matthias.fax@gmail.com>"]
license = "mit"
keywords = ["kivy", "fa", "font", "awesome", "icons"]
repository = "https://github.com/matfax/kivysome"
homepage = "https://github.com/matfax/kivysome"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
mutapath = "^0.16.0"
urllib3 = "^1.25.7"
remotezip = "^0.9.2"
lastversion = "1.2.0"
semver = "^2.10.2"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
green = "^3.0.0"
kivy = "1.11.1"
pygments = "^2.5.2"
coverage = "^5.2.1"
codecov = "^2.1.9"
black = "^20.8b1"
bandit = "^1.6.2"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "pep440"
pattern = '^v?(?P<base>\d+\.\d+\.\d+)(-?((?P<stage>[a-zA-Z]+)\.?(?P<revision>\d+)?))?$'

[build-system]
requires = ["poetry>=1.0.10", "poetry-dynamic-versioning>=0.8.3"]
build-backend = "poetry.masonry.api"
