[tool.poetry]
name = "py_midicsv"
version = "1.12.0"
description = "A library for converting MIDI files from and to CSV format"
authors = ["Tim Wedde <timwedde@icloud.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/timwedde/py_midicsv"
homepage = "https://github.com/timwedde/py_midicsv"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
pytest = "^6.0.1"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
