
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-07T14:00:15+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b47674031def1a777a2b52f7fde58e15c5ba3f8",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
