
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-02T01:30:55-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "91df4d99fd0e0b64077f9c52a48b928bf6e83d0d",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
