
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-30T22:18:16-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b97d1367823a5dc8a631c8ebae8f7eb006ad797a",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
