language: python
cache: pip
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
install:
  - pip install -r requirements.txt
script:
  - pyflakes redkyn
  - pylint redkyn
  - python setup.py nosetests
