[tool.poetry]
name = "timebandit"
version = "0.1.1"
description = "The most fabulous time measuring object in the world."
authors = ["skeptycal <skeptycal@gmail.com>"]
license = "Python-2.0"
readme = "README.md"

maintainers = ['skeptycal <skeptycal@gmail.com >']
homepage = "https://skeptycal.github.io/timebandit"
repository = "https://github.com/skeptycal/timebandit"

keywords = ['macOS', 'setup', 'profile', 'timeit', 'ci', 'tox', 'cli', 'poetry', 'pyproject', 'toml']

classifiers = [
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: Implementation :: CPython',
    'Programming Language :: Python :: Implementation :: PyPy',
]

[tool.poetry.dependencies]
python = "^3.5"
loguru = "^0.5.1"
wheel = "^0.35.1"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
tox = "^3.19.0"
coverage = "^5.2.1"
flake8 = "^3.8.3"
tox-travis  = "^0.12"
Sphinx  = "^3.2.1"
sphinx-autobuild  = "^0.7.1"
sphinx-rtd-theme  = "^0.5.0"
autopep8 = "^1.5.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
