[tool.poetry]
name = "aurcore"
version = "0.1.31"
description = "Aurcore!"
authors= ["Zenith <z@zenith.dev>"]

[tool.poetry.dependencies]
python = ">3.8"


[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"
pytest-repeat = "*"
#pytest-catchlog = "^1.2.2"
