# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mms_python_client
from mms_python_client.models.jwt_authentication_request import JwtAuthenticationRequest  # noqa: E501
from mms_python_client.rest import ApiException

class TestJwtAuthenticationRequest(unittest.TestCase):
    """JwtAuthenticationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JwtAuthenticationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mms_python_client.models.jwt_authentication_request.JwtAuthenticationRequest()  # noqa: E501
        if include_optional :
            return JwtAuthenticationRequest(
                username = '0', 
                password = '0'
            )
        else :
            return JwtAuthenticationRequest(
                username = '0',
                password = '0',
        )

    def testJwtAuthenticationRequest(self):
        """Test JwtAuthenticationRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
