# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mms_python_client
from mms_python_client.api.webhooks_api import WebhooksApi  # noqa: E501
from mms_python_client.rest import ApiException


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self):
        self.api = mms_python_client.api.webhooks_api.WebhooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_or_update_webhooks(self):
        """Test case for create_or_update_webhooks

        """
        pass

    def test_delete_webhooks(self):
        """Test case for delete_webhooks

        """
        pass

    def test_get_all_webhooks(self):
        """Test case for get_all_webhooks

        """
        pass


if __name__ == '__main__':
    unittest.main()
