# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mms_python_client
from mms_python_client.api.views_api import ViewsApi  # noqa: E501
from mms_python_client.rest import ApiException


class TestViewsApi(unittest.TestCase):
    """ViewsApi unit test stubs"""

    def setUp(self):
        self.api = mms_python_client.api.views_api.ViewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_or_update_views(self):
        """Test case for create_or_update_views

        """
        pass

    def test_get_documents(self):
        """Test case for get_documents

        """
        pass

    def test_get_groups(self):
        """Test case for get_groups

        """
        pass

    def test_get_mounts(self):
        """Test case for get_mounts

        """
        pass

    def test_get_view(self):
        """Test case for get_view

        """
        pass

    def test_get_views(self):
        """Test case for get_views

        """
        pass


if __name__ == '__main__':
    unittest.main()
