# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mms_python_client
from mms_python_client.models.project import Project  # noqa: E501
from mms_python_client.rest import ApiException

class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Project
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mms_python_client.models.project.Project()  # noqa: E501
        if include_optional :
            return Project(
                org_id = '0', 
                id = '0', 
                name = '0', 
                schema = 'default', 
                project_id = '0', 
                creator = '0', 
                doc_id = '0', 
                modifier = '0', 
                created = '0', 
                modified = '0'
            )
        else :
            return Project(
                org_id = '0',
                name = '0',
        )

    def testProject(self):
        """Test Project"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
