# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mms_python_client
from mms_python_client.models.schemas_response import SchemasResponse  # noqa: E501
from mms_python_client.rest import ApiException

class TestSchemasResponse(unittest.TestCase):
    """SchemasResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SchemasResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mms_python_client.models.schemas_response.SchemasResponse()  # noqa: E501
        if include_optional :
            return SchemasResponse(
                schemas = [
                    { }
                    ]
            )
        else :
            return SchemasResponse(
        )

    def testSchemasResponse(self):
        """Test SchemasResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
