# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mms_python_client
from mms_python_client.models.permission_lookup_response import PermissionLookupResponse  # noqa: E501
from mms_python_client.rest import ApiException

class TestPermissionLookupResponse(unittest.TestCase):
    """PermissionLookupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PermissionLookupResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mms_python_client.models.permission_lookup_response.PermissionLookupResponse()  # noqa: E501
        if include_optional :
            return PermissionLookupResponse(
                messages = [
                    '0'
                    ], 
                rejected = [
                    mms_python_client.models.rejection.Rejection(
                        object = mms_python_client.models.object.object(), 
                        code = 56, 
                        message = '0', )
                    ], 
                lookups = [
                    mms_python_client.models.permission_lookup.PermissionLookup(
                        type = 'ORG', 
                        org_id = '0', 
                        project_id = '0', 
                        ref_id = '0', 
                        privilege = 'ORG_READ', 
                        allow_anon_if_public = True, 
                        has_privilege = True, )
                    ], 
                all_passed = True
            )
        else :
            return PermissionLookupResponse(
        )

    def testPermissionLookupResponse(self):
        """Test PermissionLookupResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
