# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cogneed-protos/ai/cogneed/api/trainui/record.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cogneed_protos.ai.cogneed.api.trainui import common_pb2 as cogneed__protos_dot_ai_dot_cogneed_dot_api_dot_trainui_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cogneed-protos/ai/cogneed/api/trainui/record.proto',
  package='ai.cogneed.api.trainui.record',
  syntax='proto3',
  serialized_options=_b('\n\035ai.cogneed.api.trainui.recordP\001'),
  serialized_pb=_b('\n2cogneed-protos/ai/cogneed/api/trainui/record.proto\x12\x1d\x61i.cogneed.api.trainui.record\x1a\x32\x63ogneed-protos/ai/cogneed/api/trainui/common.proto\"p\n\x06\x43reate\x12\x15\n\rsentence_uuid\x18\x01 \x01(\t\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x14\n\x0cnum_channels\x18\x03 \x01(\x05\x12\x13\n\x0bsample_size\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\x0c\"!\n\nRecordUuid\x12\x13\n\x0brecord_uuid\x18\x01 \x01(\t\"\x19\n\x06Record\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xc4\x01\n\rRecordService\x12S\n\x06\x63reate\x12%.ai.cogneed.api.trainui.record.Create\x1a\".ai.cogneed.api.trainui.ResponseOk\x12^\n\nread_audio\x12).ai.cogneed.api.trainui.record.RecordUuid\x1a%.ai.cogneed.api.trainui.record.RecordB!\n\x1d\x61i.cogneed.api.trainui.recordP\x01\x62\x06proto3')
  ,
  dependencies=[cogneed__protos_dot_ai_dot_cogneed_dot_api_dot_trainui_dot_common__pb2.DESCRIPTOR,])




_CREATE = _descriptor.Descriptor(
  name='Create',
  full_name='ai.cogneed.api.trainui.record.Create',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence_uuid', full_name='ai.cogneed.api.trainui.record.Create.sentence_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='ai.cogneed.api.trainui.record.Create.sample_rate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_channels', full_name='ai.cogneed.api.trainui.record.Create.num_channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_size', full_name='ai.cogneed.api.trainui.record.Create.sample_size', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='ai.cogneed.api.trainui.record.Create.content', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=249,
)


_RECORDUUID = _descriptor.Descriptor(
  name='RecordUuid',
  full_name='ai.cogneed.api.trainui.record.RecordUuid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='record_uuid', full_name='ai.cogneed.api.trainui.record.RecordUuid.record_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=284,
)


_RECORD = _descriptor.Descriptor(
  name='Record',
  full_name='ai.cogneed.api.trainui.record.Record',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='ai.cogneed.api.trainui.record.Record.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=311,
)

DESCRIPTOR.message_types_by_name['Create'] = _CREATE
DESCRIPTOR.message_types_by_name['RecordUuid'] = _RECORDUUID
DESCRIPTOR.message_types_by_name['Record'] = _RECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Create = _reflection.GeneratedProtocolMessageType('Create', (_message.Message,), dict(
  DESCRIPTOR = _CREATE,
  __module__ = 'cogneed_protos.ai.cogneed.api.trainui.record_pb2'
  # @@protoc_insertion_point(class_scope:ai.cogneed.api.trainui.record.Create)
  ))
_sym_db.RegisterMessage(Create)

RecordUuid = _reflection.GeneratedProtocolMessageType('RecordUuid', (_message.Message,), dict(
  DESCRIPTOR = _RECORDUUID,
  __module__ = 'cogneed_protos.ai.cogneed.api.trainui.record_pb2'
  # @@protoc_insertion_point(class_scope:ai.cogneed.api.trainui.record.RecordUuid)
  ))
_sym_db.RegisterMessage(RecordUuid)

Record = _reflection.GeneratedProtocolMessageType('Record', (_message.Message,), dict(
  DESCRIPTOR = _RECORD,
  __module__ = 'cogneed_protos.ai.cogneed.api.trainui.record_pb2'
  # @@protoc_insertion_point(class_scope:ai.cogneed.api.trainui.record.Record)
  ))
_sym_db.RegisterMessage(Record)


DESCRIPTOR._options = None

_RECORDSERVICE = _descriptor.ServiceDescriptor(
  name='RecordService',
  full_name='ai.cogneed.api.trainui.record.RecordService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=314,
  serialized_end=510,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='ai.cogneed.api.trainui.record.RecordService.create',
    index=0,
    containing_service=None,
    input_type=_CREATE,
    output_type=cogneed__protos_dot_ai_dot_cogneed_dot_api_dot_trainui_dot_common__pb2._RESPONSEOK,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='read_audio',
    full_name='ai.cogneed.api.trainui.record.RecordService.read_audio',
    index=1,
    containing_service=None,
    input_type=_RECORDUUID,
    output_type=_RECORD,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECORDSERVICE)

DESCRIPTOR.services_by_name['RecordService'] = _RECORDSERVICE

# @@protoc_insertion_point(module_scope)
