[tool.poetry]
name = "gdict"
version = "0.1.1"
description = ""
authors = ["guojian <guojian_k@qq.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"
requests = "^2.24.0"
lxml = "^4.5.2"

[tool.poetry.dev-dependencies]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.poetry.scripts]
gdict='gdict.cli:entry'
