[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "camera-stage-mapping"
version = "0.1.4"
license = "LGPL-3.0-or-later"
readme = "README.md"
homepage = "https://gitlab.com/openflexure/microscope-extensions/camera-stage-mapping/"
description = "Calibration and mapping between stage and camera coordinates in a microscope"
authors = ["Richard Bowman <richard.bowman@cantab.net>"]

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.17"
opencv-python-headless = {version = "^4.1", optional = true} # This is critical for Raspberry Pi.  Could remove entirely with a direct crosscorrelation function...
scipy = {version = "^1.4", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.4"
openflexure-microscope-client = {version = "0.1.2", optional = true}
ipykernel = {version = "^5.2", optional = true}
matplotlib = {version = "^3.2", optional = true}
sphinx = "^3.1"
sphinx-rtd-theme = "0.5.0"
sphinx-autoapi = {version = "^1.4.0"}

[tool.poetry.extras]
correlation = ["opencv-python-headless", "scipy"]
ofmclient = ["openflexure-microscope-client"]
ipython = ["ipykernel", "matplotlib"]
all = ["opencv-python-headless", "scipy", "openflexure-microscope-client", "ipykernel", "matplotlib"]
