[tool.poetry]
name = "UnionStation"
version = "0.1.0"
description = "Big ML/DL dataset processing station"
authors = ["H-AI <dongjian413@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
protobuf = "^3.13.0"
betterproto = {version = "^2.0.0b1", extras = ["compiler"]}
boto3 = "^1.14.44"
s3fs = "^0.4.2"
urllib3 = "^1.25.10"
opencv-python = "4.2.0.34"
pyarrow = "^1.0.0"
pyspark = "^3.0.0"
tqdm = "^4.48.2"
pycocotools = "^2.0.1"
absl-py = "0.10.0"
pandas = "^1.1.1"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
black = "^19.10b0"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pre-commit = "^2.6.0"
mypy = "^0.782"
jupyterlab = "^2.2.6"


[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
