
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-03T13:59:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c7d446efc91093fc9d015e9278e2f6eb5716eedc",
 "version": "1.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
