[tool.poetry]
name = "karvi"
version = "0.4.0"
description = "A small package with custom resources for Django projects."
license = "GPL-3.0-only"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.6",
    "Framework :: Django :: 2.2",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
repository = "https://gitlab.com/aranofacundo/karvi"
authors = ["Facundo Arano <aranofacundo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
django = "~2.2"

[tool.poetry.dev-dependencies]
black = { allow-prereleases = true, version = "*" }
flake8 = "*"
rope = "*"
jedi = "*"

[tool.dephell.main]
from = { format = "poetry", path = "pyproject.toml" }
to = { format = "setuppy", path = "setup.py" }
versioning = "semver"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
