
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-31T17:52:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9058c721df5673aded4921f83dbf92b5a0f279db",
 "version": "0.3.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
