# https://python-poetry.org/docs/pyproject/
# https://www.python.org/dev/peps/pep-0621/
[tool.poetry]
name = "yocho.rdflib-xtl"
version = "0.2.0"
description = "Extra tools for rdflib"
authors = ["Iwan Aucamp <aucampia@gmail.com>"]
license = "CC0-1.0"
readme = "README.md"
packages = [
    { include = "yocho", from = "src" }
]

[tool.poetry.scripts]
"rdflib-xtl" = "yocho.rdflib_xtl.cli:main"

[tool.poetry.dependencies]
python = "^3.6"
rdflib = "^5.0.0"
owlrl = "^5.2.1"
rdflib-jsonld = "^0.5.0"
pyyaml = "^5.3.1"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.782"
pylint = "^2.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
