[metadata]
description-file = "README.md"

[build-system]
requires = ["poetry>=1,<2", "coverage[toml]>=5,<6"]
build-backend = "poetry.masonry.api"


#########################################################################################
# Poetry metadata
#########################################################################################

[tool.poetry]
name = "tyrannosaurus"
version = "0.8.0"
description = "Opinionated Python template and metadata synchronizer for 2020."
authors = ["Douglas Myers-Turnbull"]
maintainers = ["Douglas Myers-Turnbull"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["python", "template", "pyproject-toml", "python-poetry", "conda-build"]
homepage = "https://github.com/dmyersturnbull/tyrannosaurus"
repository = "https://github.com/dmyersturnbull/tyrannosaurus"
documentation = "https://tyrannosaurus.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Natural Language :: English",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
	"Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Environment :: Console",
	"Framework :: tox",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Code Generators"
]
include = [
    "README.md",
    "LICENSE.txt",
    "CHANGELOG.md"
]

[tool.poetry.urls]
CI = "https://github.com/dmyersturnbull/tyrannosaurus/actions"
Issues = "https://github.com/dmyersturnbull/tyrannosaurus/issues"
Download = "https://pypi.org/project/tyrannosaurus/"


#########################################################################################
# Tyrannosaurus
#########################################################################################

[tool.tyrannosaurus.options]
align = true

[tool.tyrannosaurus.sources]
status             = "'Development'"
date               = "'${today}'"
copyright          = "'Copyright 2020'"
version            = "tool.poetry.version"
release            = "tool.poetry.version"
pyversions         = "tool.poetry.dependencies"
devdeps            = "tool.poetry.dev-dependencies"
linelength         = "tool.black.line-length"
authors = [
    "Douglas Myers-Turnbull <github:dmyersturnbull,orcid:0000-0003-3610-4808>"
]
maintainers = "tool.tyrannosaurus.sources.authors"

[tool.tyrannosuarus.paths]
recipe             = "'recipes/${name}/meta.yaml'"
environment        = "'environment.yml'"

[tool.tyrannosaurus.targets]
pyproject    = true
init         = true
tox          = true
docs         = true
recipes      = true
license      = true
authors      = true
github       = true
travis       = true
dockerfile   = true
readme       = true
changelog    = true
citation     = true
codemeta     = true
environment  = false


#########################################################################################
# Poetry build & dependencies
#########################################################################################

[tool.poetry.scripts]
tyrannosaurus = "tyrannosaurus.cli:cli"

[tool.poetry.dependencies]
python                   = ">=3.8, <4"
tomlkit                  = ">=0.5, <1.0"
typer                    = ">=0.3, <1.0"
requests                 = "^2"
grayskull                = ">=0.8.1, <1.0"

[tool.poetry.dev-dependencies]
pre-commit               = "^2"
pytest                   = "^6"
coverage                 = {extras = ["toml"], version = "^5"}
pytest-cov               = "^2"
sphinx                   = "^3"
sphinx-autoapi           = "^1"
sphinx-rtd-theme         = ">=0.5, <1.0"
flake8                   = "^3"
flake8-docstrings        = "^1"
black                    = "=19.10b0"
isort                    = "^5"
flake8-bandit            = "^2"
flake8-bugbear           = "^20"

[tool.poetry.extras]
# auto-filled from dev-deps
dev     = [
        "pre-commit", "pytest", "coverage", "pytest-cov",
        "sphinx", "sphinx-autoapi",
        "flake8", "flake8-docstrings",
        "black", "isort",
        "flake8-bandit", "flake8-bugbear"
]


#########################################################################################
# Style checking
#########################################################################################

[tool.coverage.paths]
source = ["tyrannosaurus"]

[tool.coverage.run]
source = ["tyrannosaurus"]

[tool.coverage.report]
show_missing = true

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.isort]
line_length = 100

[pycodestyle]
max-line-length = 100
statistics = true

[pydocstyle]
# 212 and 213 contradict; 203 and 204 contradict; D302 is not relevant in Py3
# D107 isn't needed sometimes
# and the rest are just too picky
ignore = ["D107", "D200", "D203", "D205", "D212", "D302", "D400", "D403", "D409", "D411"]
