build: false

environment:
  matrix:

   - PYTHON: "C:\\Python37-x64"
     PYTHON_VERSION: "3.7.x"
     PYTHON_ARCH: "64"

   - PYTHON: "C:\\Python38"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "32"

   - PYTHON: "C:\\Python38-x64"
     PYTHON_VERSION: "3.8.x"
     PYTHON_ARCH: "64"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV%  python -m pip install -U pip"
  - "%CMD_IN_ENV%  pip install --upgrade setuptools pip"
  - "%CMD_IN_ENV%  pip install .[test]"
  - "%CMD_IN_ENV%  mkdir results"
  - "%CMD_IN_ENV%  cd results"
test_script:
  - "%CMD_IN_ENV%  pytest --pyargs -v traitlets"
