
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-02T15:34:35-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "be28093e4cf31d2b6c355846c6d6295949c950ae",
 "version": "v0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
