
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-04T12:27:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0a0b89be652cf16101a17a1c2ba4831e08fce74",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
