# coding: utf-8

"""
    MMS Example API

    Documentation for MMS API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from mms_python_client.configuration import Configuration


class Project(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'org_id': 'str',
        'id': 'str',
        'name': 'str',
        'schema': 'str',
        'project_id': 'str',
        'creator': 'str',
        'doc_id': 'str',
        'modifier': 'str',
        'created': 'str',
        'modified': 'str'
    }

    attribute_map = {
        'org_id': 'orgId',
        'id': 'id',
        'name': 'name',
        'schema': 'schema',
        'project_id': '_projectId',
        'creator': '_creator',
        'doc_id': '_docId',
        'modifier': '_modifier',
        'created': '_created',
        'modified': '_modified'
    }

    def __init__(self, org_id=None, id=None, name=None, schema='default', project_id=None, creator=None, doc_id=None, modifier=None, created=None, modified=None, local_vars_configuration=None):  # noqa: E501
        """Project - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._org_id = None
        self._id = None
        self._name = None
        self._schema = None
        self._project_id = None
        self._creator = None
        self._doc_id = None
        self._modifier = None
        self._created = None
        self._modified = None
        self.discriminator = None

        self.org_id = org_id
        if id is not None:
            self.id = id
        self.name = name
        if schema is not None:
            self.schema = schema
        if project_id is not None:
            self.project_id = project_id
        if creator is not None:
            self.creator = creator
        if doc_id is not None:
            self.doc_id = doc_id
        if modifier is not None:
            self.modifier = modifier
        if created is not None:
            self.created = created
        if modified is not None:
            self.modified = modified

    @property
    def org_id(self):
        """Gets the org_id of this Project.  # noqa: E501


        :return: The org_id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._org_id

    @org_id.setter
    def org_id(self, org_id):
        """Sets the org_id of this Project.


        :param org_id: The org_id of this Project.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and org_id is None:  # noqa: E501
            raise ValueError("Invalid value for `org_id`, must not be `None`")  # noqa: E501

        self._org_id = org_id

    @property
    def id(self):
        """Gets the id of this Project.  # noqa: E501


        :return: The id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Project.


        :param id: The id of this Project.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Project.  # noqa: E501


        :return: The name of this Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Project.


        :param name: The name of this Project.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def schema(self):
        """Gets the schema of this Project.  # noqa: E501

        Acceptable values depends on the specific build and implementation (ex. default, cameo, jupyter), if a value isn't supported, will fall back to default. This can influence the project's underlying schema used and additional validation or processing when getting or updating elements.  # noqa: E501

        :return: The schema of this Project.  # noqa: E501
        :rtype: str
        """
        return self._schema

    @schema.setter
    def schema(self, schema):
        """Sets the schema of this Project.

        Acceptable values depends on the specific build and implementation (ex. default, cameo, jupyter), if a value isn't supported, will fall back to default. This can influence the project's underlying schema used and additional validation or processing when getting or updating elements.  # noqa: E501

        :param schema: The schema of this Project.  # noqa: E501
        :type: str
        """

        self._schema = schema

    @property
    def project_id(self):
        """Gets the project_id of this Project.  # noqa: E501


        :return: The project_id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this Project.


        :param project_id: The project_id of this Project.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def creator(self):
        """Gets the creator of this Project.  # noqa: E501


        :return: The creator of this Project.  # noqa: E501
        :rtype: str
        """
        return self._creator

    @creator.setter
    def creator(self, creator):
        """Sets the creator of this Project.


        :param creator: The creator of this Project.  # noqa: E501
        :type: str
        """

        self._creator = creator

    @property
    def doc_id(self):
        """Gets the doc_id of this Project.  # noqa: E501


        :return: The doc_id of this Project.  # noqa: E501
        :rtype: str
        """
        return self._doc_id

    @doc_id.setter
    def doc_id(self, doc_id):
        """Sets the doc_id of this Project.


        :param doc_id: The doc_id of this Project.  # noqa: E501
        :type: str
        """

        self._doc_id = doc_id

    @property
    def modifier(self):
        """Gets the modifier of this Project.  # noqa: E501


        :return: The modifier of this Project.  # noqa: E501
        :rtype: str
        """
        return self._modifier

    @modifier.setter
    def modifier(self, modifier):
        """Sets the modifier of this Project.


        :param modifier: The modifier of this Project.  # noqa: E501
        :type: str
        """

        self._modifier = modifier

    @property
    def created(self):
        """Gets the created of this Project.  # noqa: E501


        :return: The created of this Project.  # noqa: E501
        :rtype: str
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Project.


        :param created: The created of this Project.  # noqa: E501
        :type: str
        """

        self._created = created

    @property
    def modified(self):
        """Gets the modified of this Project.  # noqa: E501


        :return: The modified of this Project.  # noqa: E501
        :rtype: str
        """
        return self._modified

    @modified.setter
    def modified(self, modified):
        """Sets the modified of this Project.


        :param modified: The modified of this Project.  # noqa: E501
        :type: str
        """

        self._modified = modified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Project):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Project):
            return True

        return self.to_dict() != other.to_dict()
