---
required_packages:
  - mariadb-server
  - python3-devel
  - python3-PyMySQL
  - python3-iniparse
  - libffi-devel
  - libxslt-devel
  - openssl-devel
  - libxml2-devel
  - nginx
  - uwsgi
  - uwsgi-plugin-python3
