[tool.poetry]
name = "captain-cookie"
version = "0.6.0"
description = ""
authors = ["gcharbon <guillaume.charbonnier@capgemini.com>"]

[tool.poetry.dependencies]
python = "^3.6"
cookiecutter = "^1.7.2"


[tool.poetry.dev-dependencies]
black = "^19.10b0"
bump2version = "^1.0.0"
flake8 = "^3.8.2"
pytest = "^5.4.3"
pytest-bdd = "^3.4.0"

[tool.poetry.scripts]
captain-cookie = "captain_cookie:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
